DATA32 @@RANDOM_ID@@
MOVE32_32(@@POWER@@, @@RANDOM_ID@@)
CALL(motors_overflow_check_b7f9240db9f33a5fa_util,@@RANDOM_ID@@,@@RANDOM_ID@@)
OUTPUT_POWER(0, @@PORT@@, @@RANDOM_ID@@)
OUTPUT_START(0, @@PORT@@)
