#pragma once

#include <QtCore/qglobal.h>

#ifndef QRGUI_VERSIONING_PLUGINS_MANAGER_LIBRARY
#  if defined(QRGUI_VERSIONING_PLUGINS_MANAGER_LIBRARY)
#    define QRGUI_VERSIONING_PLUGINS_MANAGER_EXPORT Q_DECL_EXPORT
#  else
#    define QRGUI_VERSIONING_PLUGINS_MANAGER_EXPORT Q_DECL_IMPORT
#  endif
#endif
