HEADERS += dialogs/plugindialog.h \
	dialogs/refWindow.h \
	dialogs/preferencesDialog.h \
	dialogs/shapeEdit/shapeEdit.h \
	dialogs/shapeEdit/scene.h \
	dialogs/shapeEdit/arch.h \
	dialogs/shapeEdit/line.h \
	dialogs/shapeEdit/item.h \
	dialogs/shapeEdit/ellipse.h \
	dialogs/shapeEdit/rectangle.h \
	dialogs/shapeEdit/text.h \
	dialogs/shapeEdit/pointPort.h \
	dialogs/shapeEdit/linePort.h \
	dialogs/shapeEdit/xmlLoader.h \
	dialogs/shapeEdit/stylus.h \
	dialogs/shapeEdit/colorListEditor.h \
	dialogs/shapeEdit/curve.h \
	dialogs/shapeEdit/view.h \
	dialogs/shapeEdit/textPicture.h \
	dialogs/shapeEdit/path.h \
	dialogs/shapeEdit/image.h \
	dialogs/preferencesPages/page.h \
	dialogs/preferencesPages/behaviourPage.h \
	dialogs/preferencesPages/compilerPage.h \
	dialogs/preferencesPages/debuggerPage.h \
	dialogs/preferencesPages/editorPage.h \
	dialogs/preferencesPages/miscellaniousPage.h \
	dialogs/gesturesShow/gesturesWidget.h \
	dialogs/checkoutdialog.h \
	dialogs/preferencesPages/featuresPage.h \

SOURCES += dialogs/plugindialog.cpp \
	dialogs/refWindow.cpp \
	dialogs/preferencesDialog.cpp \
	dialogs/shapeEdit/shapeEdit.cpp \
	dialogs/shapeEdit/scene.cpp \
	dialogs/shapeEdit/arch.cpp \
	dialogs/shapeEdit/line.cpp \
	dialogs/shapeEdit/item.cpp \
	dialogs/shapeEdit/ellipse.cpp \
	dialogs/shapeEdit/rectangle.cpp \
	dialogs/shapeEdit/text.cpp \
	dialogs/shapeEdit/pointPort.cpp \
	dialogs/shapeEdit/linePort.cpp \
	dialogs/shapeEdit/xmlLoader.cpp \
	dialogs/shapeEdit/stylus.cpp \
	dialogs/shapeEdit/colorListEditor.cpp \
	dialogs/shapeEdit/path.cpp \
	dialogs/shapeEdit/curve.cpp \
	dialogs/shapeEdit/view.cpp \
	dialogs/shapeEdit/textPicture.cpp \
	dialogs/shapeEdit/image.cpp \
	dialogs/gesturesShow/gesturesWidget.cpp \
	dialogs/preferencesPages/behaviourPage.cpp \
	dialogs/preferencesPages/compilerPage.cpp \
	dialogs/preferencesPages/debuggerPage.cpp \
	dialogs/preferencesPages/editorPage.cpp \
	dialogs/preferencesPages/miscellaniousPage.cpp \
	dialogs/checkoutdialog.cpp \
	dialogs/preferencesPages/featuresPage.cpp \

FORMS += dialogs/editorGeneratorDialog.ui \
	dialogs/preferencesDialog.ui \
	dialogs/shapeEdit/shapeEdit.ui \
	dialogs/gesturesShow/gesturesWidget.ui \
	dialogs/preferencesPages/miscellaniousPage.ui \
	dialogs/preferencesPages/editorPage.ui \
	dialogs/preferencesPages/debuggerPage.ui \
	dialogs/preferencesPages/compilerPage.ui \
	dialogs/preferencesPages/behaviourPage.ui \
	dialogs/refWindow.ui \
	dialogs/preferencesPages/featuresPage.ui
