HEADERS += \
	$$PWD/gesturesShow/gesturesWidget.h \
	$$PWD/metamodelingOnFly/propertiesDialog.h \
	$$PWD/metamodelingOnFly/editPropertiesDialog.h \
	$$PWD/metamodelingOnFly/chooseTypeDialog.h \
	$$PWD/metamodelingOnFly/edgePropertiesDialog.h \
	$$PWD/metamodelingOnFly/addNodeDialog.h \
	$$PWD/preferencesPages/behaviourPage.h \
	$$PWD/preferencesPages/debuggerPage.h \
	$$PWD/preferencesPages/editorPage.h \
	$$PWD/preferencesPages/miscellaniousPage.h \
	$$PWD/preferencesPages/featuresPage.h \
	$$PWD/preferencesPages/preferencesPage.h \
	$$PWD/progressDialog/progressBar.h \
	$$PWD/progressDialog/progressDialog.h \
	$$PWD/findReplaceDialog.h \
	$$PWD/managedClosableDialog.h \
	$$PWD/preferencesDialog.h \
	$$PWD/suggestToCreateDiagramDialog.h \
	$$PWD/suggestToCreateProjectDialog.h \
	$$PWD/renameDialog.h \
	$$PWD/metamodelingOnFly/restorePropertiesDialog.h \

SOURCES += \
	$$PWD/gesturesShow/gesturesWidget.cpp \
	$$PWD/metamodelingOnFly/propertiesDialog.cpp \
	$$PWD/metamodelingOnFly/editPropertiesDialog.cpp \
	$$PWD/metamodelingOnFly/chooseTypeDialog.cpp \
	$$PWD/metamodelingOnFly/edgePropertiesDialog.cpp \
	$$PWD/metamodelingOnFly/addNodeDialog.cpp \
	$$PWD/preferencesPages/behaviourPage.cpp \
	$$PWD/preferencesPages/debuggerPage.cpp \
	$$PWD/preferencesPages/editorPage.cpp \
	$$PWD/preferencesPages/miscellaniousPage.cpp \
	$$PWD/preferencesPages/featuresPage.cpp \
	$$PWD/progressDialog/progressBar.cpp \
	$$PWD/progressDialog/progressDialog.cpp \
	$$PWD/findReplaceDialog.cpp \
	$$PWD/managedClosableDialog.cpp \
	$$PWD/preferencesDialog.cpp \
	$$PWD/suggestToCreateDiagramDialog.cpp \
	$$PWD/suggestToCreateProjectDialog.cpp \
	$$PWD/renameDialog.cpp \
	$$PWD/metamodelingOnFly/restorePropertiesDialog.cpp \

FORMS += \
	$$PWD/gesturesShow/gesturesWidget.ui \
	$$PWD/metamodelingOnFly/propertiesDialog.ui \
	$$PWD/metamodelingOnFly/editPropertiesDialog.ui \
	$$PWD/metamodelingOnFly/chooseTypeDialog.ui \
	$$PWD/metamodelingOnFly/edgePropertiesDialog.ui \
	$$PWD/metamodelingOnFly/addNodeDialog.ui \
	$$PWD/preferencesPages/miscellaniousPage.ui \
	$$PWD/preferencesPages/editorPage.ui \
	$$PWD/preferencesPages/debuggerPage.ui \
	$$PWD/preferencesPages/behaviourPage.ui \
	$$PWD/preferencesPages/featuresPage.ui \
	$$PWD/findReplaceDialog.ui \
	$$PWD/preferencesDialog.ui \
	$$PWD/metamodelingOnFly/restorePropertiesDialog.ui \
