#include "implementation.oil"

CPU ATMEL_AT91SAM7S256
{
	OS LEJOS_OSEK
	{
		STATUS = EXTENDED;
		STARTUPHOOK = FALSE;
		ERRORHOOK = FALSE;
		SHUTDOWNHOOK = FALSE;
		PRETASKHOOK = FALSE;
		POSTTASKHOOK = FALSE;
		USEGETSERVICEID = FALSE;
		USEPARAMETERACCESS = FALSE;
		USERESSCHEDULER = FALSE;
	};

	APPMODE appmode1{};

@@TASKS@@

	EVENT TASK_MAIN_TIMER
	{
		MASK = AUTO;
	};

	TASK TASK_MAIN
	{
		AUTOSTART = TRUE
		{
			APPMODE = appmode1;
		};
		PRIORITY = 1; /* lowest priority */
		ACTIVATION = 1;
		SCHEDULE = FULL;
		STACKSIZE = 512;
		EVENT = TASK_MAIN_TIMER;
	};
	
};
