EVENT TASK_@@NAME@@_TIMER
{
	MASK = AUTO;
};

TASK TASK_@@NAME@@
{
	AUTOSTART = FALSE;
	PRIORITY = 1; /* lowest priority */
	ACTIVATION = 1;
	SCHEDULE = FULL;
	STACKSIZE = 512;
	EVENT = TASK_@@NAME@@_TIMER;
};
