DATA32 @@RANDOM_ID_1@@
MOVE32_32(@@INITIAL_VALUE@@, @@RANDOM_ID_1@@)
@@RANDOM_ID_2@@:
JR_LTEQ32(@@BOUND@@, @@RANDOM_ID_1@@, @@RANDOM_ID_3@@)
@@BODY@@
ADD32(1, @@RANDOM_ID_1@@, @@RANDOM_ID_1@@)
JR(@@RANDOM_ID_2@@)
@@RANDOM_ID_3@@:
