HEADERS += mainwindow/mainWindow.h \
	mainwindow/paletteToolbox.h \
	mainwindow/propertyEditorProxyModel.h \
	mainwindow/propertyEditorDelegate.h \
	mainwindow/errorReporter.h \
	mainwindow/openShapeEditorButton.h \
	mainwindow/shapeEdit/shapeEdit.h \
	mainwindow/shapeEdit/scene.h \
	mainwindow/shapeEdit/arch.h \
	mainwindow/shapeEdit/line.h \
	mainwindow/shapeEdit/item.h \
	mainwindow/shapeEdit/ellipse.h \
	mainwindow/shapeEdit/rectangle.h \
	mainwindow/shapeEdit/text.h \
	mainwindow/shapeEdit/pointPort.h \
	mainwindow/shapeEdit/linePort.h \
	mainwindow/shapeEdit/xmlLoader.h \
	mainwindow/shapeEdit/stylus.h \
	mainwindow/shapeEdit/colorListEditor.h \
	mainwindow/shapeEdit/curve.h \
	mainwindow/shapeEdit/view.h \
	mainwindow/gesturesShow/gesturesWidget.h \
	mainwindow/gesturesPainterInterface.h \
	mainwindow/preferencesDialog.h \
	mainwindow/gesturesPainterInterface.h \
	mainwindow/buttonRefWindow.h \
	mainwindow/refWindow.h \
	mainwindow/shapeEdit/textPicture.h \
	mainwindow/shapeEdit/path.h \
	mainwindow/shapeEdit/image.h \
	mainwindow/error.h \
	mainwindow/errorListWidget.h \
	mainwindow/mainWindowInterpretersInterface.h \
	mainwindow/preferencesPages/page.h \
	mainwindow/preferencesPages/behaviourPage.h \
	mainwindow/preferencesPages/compilerPage.h \
	mainwindow/preferencesPages/debuggerPage.h \
	mainwindow/preferencesPages/editorPage.h \
	mainwindow/preferencesPages/miscellaniousPage.h \
	mainwindow/preferencesPages/robotSettingsPage.h

SOURCES += mainwindow/mainWindow.cpp \
	mainwindow/paletteToolbox.cpp \
	mainwindow/propertyEditorProxyModel.cpp \
	mainwindow/propertyEditorDelegate.cpp \
	mainwindow/errorReporter.cpp \
	mainwindow/openShapeEditorButton.cpp \
	mainwindow/shapeEdit/shapeEdit.cpp \
	mainwindow/shapeEdit/scene.cpp \
	mainwindow/shapeEdit/arch.cpp \
	mainwindow/shapeEdit/line.cpp \
	mainwindow/shapeEdit/item.cpp \
	mainwindow/shapeEdit/ellipse.cpp \
	mainwindow/shapeEdit/rectangle.cpp \
	mainwindow/shapeEdit/text.cpp \
	mainwindow/shapeEdit/pointPort.cpp \
	mainwindow/shapeEdit/linePort.cpp \
	mainwindow/shapeEdit/xmlLoader.cpp \
	mainwindow/shapeEdit/stylus.cpp \
	mainwindow/shapeEdit/colorListEditor.cpp \
	mainwindow/shapeEdit/path.cpp \
	mainwindow/shapeEdit/curve.cpp \
	mainwindow/shapeEdit/view.cpp \
	mainwindow/gesturesShow/gesturesWidget.cpp \
	mainwindow/preferencesDialog.cpp \
	mainwindow/buttonRefWindow.cpp \
	mainwindow/refWindow.cpp \
	mainwindow/shapeEdit/textPicture.cpp \
	mainwindow/shapeEdit/image.cpp \
	mainwindow/error.cpp \
	mainwindow/errorListWidget.cpp \
	mainwindow/preferencesPages/behaviourPage.cpp \
	mainwindow/preferencesPages/compilerPage.cpp \
	mainwindow/preferencesPages/debuggerPage.cpp \
	mainwindow/preferencesPages/editorPage.cpp \
	mainwindow/preferencesPages/miscellaniousPage.cpp \
	mainwindow/preferencesPages/robotSettingsPage.cpp \


FORMS += mainwindow/mainWindow.ui \
	mainwindow/shapeEdit/shapeEdit.ui \
	mainwindow/gesturesShow/gesturesWidget.ui \
	mainwindow/preferencesDialog.ui \
	mainwindow/refWindow.ui \
	mainwindow/preferencesPages/robotSettingsPage.ui \
	mainwindow/preferencesPages/miscellaniousPage.ui \
	mainwindow/preferencesPages/editorPage.ui \
	mainwindow/preferencesPages/debuggerPage.ui \
	mainwindow/preferencesPages/compilerPage.ui \
	mainwindow/preferencesPages/behaviourPage.ui
