local Ev = {};

Ev.ENGINES_ARM = 39
Ev.ENGINES_DISARM = 38
Ev.MCE_TAKEOFF = 1
Ev.MCE_LANDING = 69

Ev.POINT_REACHED = 31
Ev.ENGINES_STARTED = 44
Ev.COPTER_LANDED = 15
Ev.BATTERY_LOW = 24
Ev.COPTER_FAIL = 2
-- Ev.ALTITUDE_REACHED = 5
 
return Ev;