var mainWindow = api.ui().mainWindow();
assert(mainWindow != null);
api.changeWindow(mainWindow);
api.wait(1500);
var newProject = api.ui().widget("QToolButton", "actionNewProject");
assert(newProject != null);
expectDialog(mainWindow, "Create project", "Diagram", 5000);
api.cursor().moveTo(newProject, 400);
api.cursor().leftButtonPress(newProject);
api.cursor().leftButtonRelease(newProject, 400);
api.wait(500);
