#include "implementation.oil"

CPU ATMEL_AT91SAM7S256
{
	OS LEJOS_OSEK
	{
		STATUS = EXTENDED;
		STARTUPHOOK = FALSE;
		ERRORHOOK = FALSE;
		SHUTDOWNHOOK = FALSE;
		PRETASKHOOK = FALSE;
		POSTTASKHOOK = FALSE;
		USEGETSERVICEID = FALSE;
		USEPARAMETERACCESS = FALSE;
		USERESSCHEDULER = FALSE;
	};

	/* Definition of application mode */
	APPMODE appmode1{};

	/* Definition of OSEK_Task*/
@@TASK@@
};
