HEADERS += \
	details/blocks/block.h \
	details/blocks/dummyBlock.h \
	details/blocks/timerBlock.h \
	details/blocks/beepBlock.h \
	details/blocks/playToneBlock.h \
	details/blocks/initialBlock.h \
	details/blocks/finalBlock.h \
	details/blocks/waitForTouchSensorBlock.h \
	details/blocks/waitForSonarDistanceBlock.h \
	details/blocks/engineCommandBlock.h \
	details/blocks/enginesForwardBlock.h \
	details/blocks/enginesBackwardBlock.h \
	details/blocks/enginesStopBlock.h \
	details/blocks/loopBlock.h \
	details/blocks/forkBlock.h \
	details/blocks/waitForColorBlock.h \
	details/blocks/waitForColorIntensityBlock.h \
	details/blocks/functionBlock.h \
	details/blocks/ifBlock.h \
	details/blocks/waitForEncoderBlock.h \
	details/blocks/nullificationEncoderBlock.h \
	details/blocks/waitForLightSensorBlock.h \
	details/blocks/waitBlock.h \
	details/blocks/waitForSensorBlock.h \
	details/blocks/waitForColorSensorBlockBase.h \
	details/blocks/waitForSoundSensorBlock.h \
	details/blocks/waitforGyroscopeSensorBlock.h \
	details/blocks/waitForAccelerometerBlock.h \
	details/blocks/commentBlock.h \
	details/blocks/waitForButtonsBlock.h \
	details/blocks/drawPixelBlock.h \
	details/blocks/drawLineBlock.h \
	details/blocks/drawCircleBlock.h \
	details/blocks/printTextBlock.h \
	details/blocks/drawRectBlock.h \
	details/blocks/clearScreenBlock.h \
	details/blocks/subprogramBlock.h \
	details/blocks/smileBlockBase.h \
	details/blocks/smileBlock.h \
	details/blocks/sadSmileBlock.h \

SOURCES +=\
	details/blocks/block.cpp \
	details/blocks/dummyBlock.cpp \
	details/blocks/timerBlock.cpp \
	details/blocks/beepBlock.cpp \
	details/blocks/playToneBlock.cpp \
	details/blocks/initialBlock.cpp \
	details/blocks/finalBlock.cpp \
	details/blocks/waitForTouchSensorBlock.cpp \
	details/blocks/waitForSonarDistanceBlock.cpp \
	details/blocks/engineCommandBlock.cpp \
	details/blocks/enginesForwardBlock.cpp \
	details/blocks/enginesBackwardBlock.cpp \
	details/blocks/enginesStopBlock.cpp \
	details/blocks/loopBlock.cpp \
	details/blocks/forkBlock.cpp \
	details/blocks/waitForColorBlock.cpp \
	details/blocks/waitForColorIntensityBlock.cpp \
	details/blocks/functionBlock.cpp \
	details/blocks/ifBlock.cpp \
	details/blocks/waitForEncoderBlock.cpp \
	details/blocks/nullificationEncoderBlock.cpp \
	details/blocks/waitForLightSensorBlock.cpp \
	details/blocks/waitBlock.cpp \
	details/blocks/waitForSensorBlock.cpp \
	details/blocks/waitForColorSensorBlockBase.cpp \
	details/blocks/waitForSoundSensorBlock.cpp \
	details/blocks/waitForAccelerometerBlock.cpp \
	details/blocks/waitForGyroscopeSensorBlock.cpp \
	details/blocks/commentBlock.cpp \
	details/blocks/waitForButtonsBlock.cpp \
	details/blocks/drawPixelBlock.cpp \
	details/blocks/drawLineBlock.cpp \
	details/blocks/drawCircleBlock.cpp \
	details/blocks/printTextBlock.cpp \
	details/blocks/drawRectBlock.cpp \
	details/blocks/clearScreenBlock.cpp \
	details/blocks/subprogramBlock.cpp \
	details/blocks/smileBlockBase.cpp \
	details/blocks/smileBlock.cpp \
	details/blocks/sadSmileBlock.cpp \
