..\bin\testAddition.exe
..\bin\testConj.exe
..\bin\testCplxAcos.exe
..\bin\testDisp.exe
..\bin\testDoubleAbs.exe
..\bin\testDoubleAcosh.exe
..\bin\testDoubleChol.exe
..\bin\testDoubleComplex.exe
..\bin\testDoubleConv.exe
..\bin\testDoubleConv2d.exe
..\bin\testDoubleCrossCorr.exe
..\bin\testDoubleDeterm.exe
..\bin\testDoubleDist.exe
..\bin\testDoubleFft.exe
..\bin\testDoubleFftShift.exe
..\bin\testDoubleFill.exe
..\bin\testDoubleIfft.exe
..\bin\testDoubleImplicitList.exe
..\bin\testDoubleLev.exe
..\bin\testDoubleLevin.exe
..\bin\testDoubleLogm.exe
..\bin\testDoubleLpc2cep.exe
..\bin\testDoubleMagnitude.exe
..\bin\testDoubleMatrixConcatenation.exe
..\bin\testDoubleMatrixMultiplication.exe
..\bin\testDoubleMax.exe
..\bin\testDoubleMean.exe
..\bin\testDoubleMin.exe
..\bin\testDoublePowm.exe
..\bin\testDoubleProd.exe
..\bin\testDoubleSpec.exe
..\bin\testDoubleSpec2.exe
..\bin\testDoubleSquaredMagnitude.exe
..\bin\testDoubleSum.exe
..\bin\testDoubleVariance.exe
..\bin\testDoubleVarianceNono.exe
..\bin\testFind.exe
..\bin\testFind2d.exe
..\bin\testFloatAbs.exe
..\bin\testFloatAcosh.exe
..\bin\testFloatChol.exe
..\bin\testFloatComplex.exe
..\bin\testFloatConv.exe
..\bin\testFloatConv2d.exe
..\bin\testFloatCrossCorr.exe
..\bin\testFloatDeterm.exe
..\bin\testFloatDist.exe
..\bin\testFloatFft.exe
..\bin\testFloatFftShift.exe
..\bin\testFloatFill.exe
..\bin\testFloatIfft.exe
..\bin\testFloatImplicitList.exe
..\bin\testFloatLev.exe
..\bin\testFloatLevin.exe
..\bin\testFloatLogm.exe
..\bin\testFloatLpc2cep.exe
..\bin\testFloatMagnitude.exe
..\bin\testFloatMatrixConcatenation.exe
..\bin\testFloatMatrixMultiplication.exe
..\bin\testFloatMax.exe
..\bin\testFloatMean.exe
..\bin\testFloatMin.exe
..\bin\testFloatPowm.exe
..\bin\testFloatProd.exe
..\bin\testFloatSpec.exe
..\bin\testFloatSpec2.exe
..\bin\testFloatSquaredMagnitude.exe
..\bin\testFloatSum.exe
..\bin\testFloatVariance.exe
..\bin\testFloatVarianceNono.exe
..\bin\testFrexp.exe
..\bin\testHilbert.exe
..\bin\testIsEmpty.exe
..\bin\testIsNan.exe
..\bin\testJmat.exe
..\bin\testLDivision.exe
..\bin\testLength.exe
..\bin\testMatFft.exe
..\bin\testMatIfft.exe
..\bin\testMatrixExponential.exe
..\bin\testMatrixEye.exe
..\bin\testMatrixInfiniteNorm.exe
..\bin\testMatrixInversion.exe
..\bin\testMatrixLDivision.exe
..\bin\testMatrixOnes.exe
..\bin\testMatrixRDivision.exe
..\bin\testMatrixTrace.exe
..\bin\testMatrixTranspose.exe
..\bin\testMatrixZeros.exe
..\bin\testMultiplication.exe
..\bin\testPythag.exe
..\bin\testRand.exe
..\bin\testRDivision.exe
..\bin\testRealsAcos.exe
..\bin\testSign.exe
..\bin\testSize.exe
..\bin\testString.exe
..\bin\testSubtraction.exe
..\bin\testType.exe
