#include "implementation.oil"

CPU ATMEL_AT91SAM7S256
{
	OS LEJOS_OSEK
	{
		STATUS = EXTENDED;
		STARTUPHOOK = FALSE;
		ERRORHOOK = FALSE;
		SHUTDOWNHOOK = FALSE;
		PRETASKHOOK = FALSE;
		POSTTASKHOOK = FALSE;
		USEGETSERVICEID = FALSE;
		USEPARAMETERACCESS = FALSE;
		USERESSCHEDULER = FALSE;
	};

	APPMODE appmode1{};

@@TASKS@@

@@MAIN_TASK@@
};
