# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------


#Header files
HEADERS += ./ProjectTypeFixer.h \
    ./SolutionFileFixer.h \
    ./Fixer.h

#Source files
SOURCES += ./main.cpp \
    ./ProjectTypeFixer.cpp \
    ./SolutionFileFixer.cpp \
    ./Fixer.cpp
