HEADERS += \
	elementEditor/elementEditor.h \
	elementEditor/shapeEdit/shapeEdit.h \
	elementEditor/shapeEdit/scene.h \
	elementEditor/shapeEdit/arch.h \
	elementEditor/shapeEdit/line.h \
	elementEditor/shapeEdit/item.h \
	elementEditor/shapeEdit/ellipse.h \
	elementEditor/shapeEdit/rectangle.h \
	elementEditor/shapeEdit/text.h \
	elementEditor/shapeEdit/pointPort.h \
	elementEditor/shapeEdit/linePort.h \
	elementEditor/shapeEdit/xmlLoader.h \
	elementEditor/shapeEdit/stylus.h \
	elementEditor/shapeEdit/colorListEditor.h \
	elementEditor/shapeEdit/curve.h \
	elementEditor/shapeEdit/view.h \
	elementEditor/shapeEdit/textPicture.h \
	elementEditor/shapeEdit/path.h \
	elementEditor/shapeEdit/image.h \
	elementEditor/widgetsEdit/widgetsEditor.h \
	elementEditor/widgetsEdit/private/toolFactory.h \
	elementEditor/widgetsEdit/private/toolList.h \
	elementEditor/widgetsEdit/private/layoutButton.h \
	elementEditor/widgetsEdit/private/toolController.h \
	elementEditor/widgetsEdit/private/layoutButtons.h \
	elementEditor/widgetsEdit/private/editorScene.h \
	elementEditor/widgetsEdit/private/propertyBrowserController.h \
	elementEditor/widgetsEdit/tools/tool.h \
	elementEditor/widgetsEdit/tools/layoutTool.h \
	elementEditor/widgetsEdit/tools/root.h \
	elementEditor/widgetsEdit/tools/rootWidget.h \
	elementEditor/widgetsEdit/tools/checkBox.h \
	elementEditor/widgetsEdit/tools/comboBox.h \
	elementEditor/widgetsEdit/tools/groupBox.h \
	elementEditor/widgetsEdit/tools/pushButton.h \
	elementEditor/widgetsEdit/tools/radioButton.h \
	elementEditor/widgetsEdit/tools/scrollArea.h \
	elementEditor/widgetsEdit/tools/frame.h \
	elementEditor/widgetsEdit/tools/widget.h \
	elementEditor/widgetsEdit/tools/lineEdit.h \
	elementEditor/widgetsEdit/tools/plainTextEdit.h \
	elementEditor/widgetsEdit/tools/spinBox.h \
	elementEditor/widgetsEdit/tools/doubleSpinBox.h \
	elementEditor/widgetsEdit/tools/label.h \
	elementEditor/widgetsEdit/tools/layoutHelpers/layoutHelperBase.h \
	elementEditor/widgetsEdit/tools/layoutHelpers/gridLayoutHelper.h \
	elementEditor/widgetsEdit/tools/layoutHelpers/linearLayoutHelper.h \
	elementEditor/widgetsEdit/tools/layoutHelpers/layoutTypes.h \
	elementEditor/widgetsEdit/tools/layoutHelpers/layoutHelperFactory.h \
	elementEditor/widgetsEdit/tools/propertyManagers/property.h \
	elementEditor/widgetsEdit/tools/propertyManagers/propertyManagerBase.h \
	elementEditor/widgetsEdit/tools/propertyManagers/toolPropertyManager.h \
	elementEditor/widgetsEdit/tools/propertyManagers/rootPropertyManager.h \
	elementEditor/widgetsEdit/tools/propertyManagers/checkBoxPropertyManager.h \
	elementEditor/widgetsEdit/tools/propertyManagers/buttonPropertyManagerBase.h \
	elementEditor/widgetsEdit/tools/propertyManagers/pushButtonPropertyManager.h \
	elementEditor/widgetsEdit/tools/propertyManagers/radioButtonPropertyManager.h \
	elementEditor/widgetsEdit/tools/propertyManagers/layoutToolPropertyManager.h \
	elementEditor/widgetsEdit/tools/propertyManagers/groupBoxPropertyManager.h \
	elementEditor/widgetsEdit/tools/propertyManagers/framePropertyManager.h \
	elementEditor/widgetsEdit/tools/propertyManagers/scrollAreaPropertyManager.h \
	elementEditor/widgetsEdit/tools/propertyManagers/widgetPropertyManager.h \
	elementEditor/widgetsEdit/tools/propertyManagers/comboBoxPropertyManager.h \
	elementEditor/widgetsEdit/tools/propertyManagers/lineEditPropertyManager.h \
	elementEditor/widgetsEdit/tools/propertyManagers/plainTextEditPropertyManager.h \
	elementEditor/widgetsEdit/tools/propertyManagers/abstractScrollAreaPropertyManager.h \
	elementEditor/widgetsEdit/tools/abstractScrollArea.h \
	elementEditor/widgetsEdit/tools/propertyManagers/abstractSpinBoxPropertyManager.h \
	elementEditor/widgetsEdit/tools/abstractSpinBox.h \
	elementEditor/widgetsEdit/tools/propertyManagers/spinBoxPropertyManager.h \
	elementEditor/widgetsEdit/tools/propertyManagers/doubleSpinBoxPropertyManager.h \
	elementEditor/widgetsEdit/tools/propertyManagers/labelPropertyManager.h \
    elementEditor/widgetsEdit/tools/spacer.h \
    elementEditor/widgetsEdit/tools/propertyManagers/spacerPropertyManager.h \
    elementEditor/widgetsEdit/tools/propertyManagers/propertyManager.h \
    elementEditor/widgetsEdit/tools/abstractButton.h

SOURCES += \
	elementEditor/elementEditor.cpp \
	elementEditor/shapeEdit/shapeEdit.cpp \
	elementEditor/shapeEdit/scene.cpp \
	elementEditor/shapeEdit/arch.cpp \
	elementEditor/shapeEdit/line.cpp \
	elementEditor/shapeEdit/item.cpp \
	elementEditor/shapeEdit/ellipse.cpp \
	elementEditor/shapeEdit/rectangle.cpp \
	elementEditor/shapeEdit/text.cpp \
	elementEditor/shapeEdit/pointPort.cpp \
	elementEditor/shapeEdit/linePort.cpp \
	elementEditor/shapeEdit/xmlLoader.cpp \
	elementEditor/shapeEdit/stylus.cpp \
	elementEditor/shapeEdit/colorListEditor.cpp \
	elementEditor/shapeEdit/path.cpp \
	elementEditor/shapeEdit/curve.cpp \
	elementEditor/shapeEdit/view.cpp \
	elementEditor/shapeEdit/textPicture.cpp \
	elementEditor/shapeEdit/image.cpp \
	elementEditor/widgetsEdit/widgetsEditor.cpp \
	elementEditor/widgetsEdit/private/toolFactory.cpp \
	elementEditor/widgetsEdit/private/toolList.cpp \
	elementEditor/widgetsEdit/private/layoutButton.cpp \
	elementEditor/widgetsEdit/private/toolController.cpp \
	elementEditor/widgetsEdit/private/layoutButtons.cpp \
	elementEditor/widgetsEdit/private/editorScene.cpp \
	elementEditor/widgetsEdit/private/propertyBrowserController.cpp \
	elementEditor/widgetsEdit/tools/tool.cpp \
	elementEditor/widgetsEdit/tools/layoutTool.cpp \
	elementEditor/widgetsEdit/tools/root.cpp \
	elementEditor/widgetsEdit/tools/rootWidget.cpp \
	elementEditor/widgetsEdit/tools/checkBox.cpp \
	elementEditor/widgetsEdit/tools/comboBox.cpp \
	elementEditor/widgetsEdit/tools/groupBox.cpp \
	elementEditor/widgetsEdit/tools/pushButton.cpp \
	elementEditor/widgetsEdit/tools/radioButton.cpp \
	elementEditor/widgetsEdit/tools/scrollArea.cpp \
	elementEditor/widgetsEdit/tools/frame.cpp \
	elementEditor/widgetsEdit/tools/widget.cpp \
	elementEditor/widgetsEdit/tools/lineEdit.cpp \
	elementEditor/widgetsEdit/tools/plainTextEdit.cpp \
	elementEditor/widgetsEdit/tools/spinBox.cpp \
	elementEditor/widgetsEdit/tools/doubleSpinBox.cpp \
	elementEditor/widgetsEdit/tools/label.cpp \
	elementEditor/widgetsEdit/tools/layoutHelpers/layoutHelperBase.cpp \
	elementEditor/widgetsEdit/tools/layoutHelpers/gridLayoutHelper.cpp \
	elementEditor/widgetsEdit/tools/layoutHelpers/linearLayoutHelper.cpp \
	elementEditor/widgetsEdit/tools/layoutHelpers/layoutHelperFactory.cpp \
	elementEditor/widgetsEdit/tools/propertyManagers/property.cpp \
	elementEditor/widgetsEdit/tools/propertyManagers/propertyManagerBase.cpp \
	elementEditor/widgetsEdit/tools/propertyManagers/toolPropertyManager.cpp \
	elementEditor/widgetsEdit/tools/propertyManagers/rootPropertyManager.cpp \
	elementEditor/widgetsEdit/tools/propertyManagers/checkBoxPropertyManager.cpp \
	elementEditor/widgetsEdit/tools/propertyManagers/buttonPropertyManagerBase.cpp \
	elementEditor/widgetsEdit/tools/propertyManagers/pushButtonPropertyManager.cpp \
	elementEditor/widgetsEdit/tools/propertyManagers/radioButtonPropertyManager.cpp \
	elementEditor/widgetsEdit/tools/propertyManagers/layoutToolPropertyManager.cpp \
	elementEditor/widgetsEdit/tools/propertyManagers/groupBoxPropertyManager.cpp \
	elementEditor/widgetsEdit/tools/propertyManagers/framePropertyManager.cpp \
	elementEditor/widgetsEdit/tools/propertyManagers/scrollAreaPropertyManager.cpp \
	elementEditor/widgetsEdit/tools/propertyManagers/widgetPropertyManager.cpp \
	elementEditor/widgetsEdit/tools/propertyManagers/comboBoxPropertyManager.cpp \
	elementEditor/widgetsEdit/tools/propertyManagers/lineEditPropertyManager.cpp \
	elementEditor/widgetsEdit/tools/propertyManagers/plainTextEditPropertyManager.cpp \
	elementEditor/widgetsEdit/tools/propertyManagers/abstractScrollAreaPropertyManager.cpp \
	elementEditor/widgetsEdit/tools/abstractScrollArea.cpp \
	elementEditor/widgetsEdit/tools/propertyManagers/abstractSpinBoxPropertyManager.cpp \
	elementEditor/widgetsEdit/tools/abstractSpinBox.cpp \
	elementEditor/widgetsEdit/tools/propertyManagers/spinBoxPropertyManager.cpp \
	elementEditor/widgetsEdit/tools/propertyManagers/doubleSpinBoxPropertyManager.cpp \
	elementEditor/widgetsEdit/tools/propertyManagers/labelPropertyManager.cpp \
    elementEditor/widgetsEdit/tools/spacer.cpp \
    elementEditor/widgetsEdit/tools/propertyManagers/spacerPropertyManager.cpp \
    elementEditor/widgetsEdit/tools/propertyManagers/propertyManager.cpp \
    elementEditor/widgetsEdit/tools/abstractButton.cpp


FORMS += \
	elementEditor/shapeEdit/shapeEdit.ui \
	elementEditor/widgetsEdit/widgetsEditor.ui \
