HEADERS += \
	$$PWD/common/startPage.h \
	$$PWD/common/templateDocumentBuilder.h \
	$$PWD/common/controlButtons.h \
	$$PWD/shapeEdit/shapeEdit.h \
	$$PWD/shapeEdit/scene.h \
	$$PWD/shapeEdit/arch.h \
	$$PWD/shapeEdit/line.h \
	$$PWD/shapeEdit/item.h \
	$$PWD/shapeEdit/ellipse.h \
	$$PWD/shapeEdit/rectangle.h \
	$$PWD/shapeEdit/text.h \
	$$PWD/shapeEdit/pointPort.h \
	$$PWD/shapeEdit/linePort.h \
	$$PWD/shapeEdit/xmlLoader.h \
	$$PWD/shapeEdit/stylus.h \
	$$PWD/shapeEdit/colorListEditor.h \
	$$PWD/shapeEdit/curve.h \
	$$PWD/shapeEdit/view.h \
	$$PWD/shapeEdit/textPicture.h \
	$$PWD/shapeEdit/path.h \
	$$PWD/shapeEdit/image.h \
	$$PWD/shapeEdit/visibilityConditionsDialog.h \
	$$PWD/shapeEdit/visibilityValueWidget.h \
	$$PWD/widgetsEdit/widgetsEditor.h \
	$$PWD/widgetsEdit/private/toolFactory.h \
	$$PWD/widgetsEdit/private/toolList.h \
	$$PWD/widgetsEdit/private/layoutButton.h \
	$$PWD/widgetsEdit/private/toolController.h \
	$$PWD/widgetsEdit/private/layoutButtons.h \
	$$PWD/widgetsEdit/private/editorScene.h \
	$$PWD/widgetsEdit/private/propertyBrowserController.h \
	$$PWD/widgetsEdit/tools/propertyManager.h \
	$$PWD/widgetsEdit/tools/property.h \
	$$PWD/widgetsEdit/tools/tool.h \
	$$PWD/widgetsEdit/tools/layoutTool.h \
	$$PWD/widgetsEdit/tools/root.h \
	$$PWD/widgetsEdit/tools/rootWidget.h \
	$$PWD/widgetsEdit/tools/checkBox.h \
	$$PWD/widgetsEdit/tools/comboBox.h \
	$$PWD/widgetsEdit/tools/groupBox.h \
	$$PWD/widgetsEdit/tools/pushButton.h \
	$$PWD/widgetsEdit/tools/radioButton.h \
	$$PWD/widgetsEdit/tools/scrollArea.h \
	$$PWD/widgetsEdit/tools/frame.h \
	$$PWD/widgetsEdit/tools/widget.h \
	$$PWD/widgetsEdit/tools/lineEdit.h \
	$$PWD/widgetsEdit/tools/plainTextEdit.h \
	$$PWD/widgetsEdit/tools/spinBox.h \
	$$PWD/widgetsEdit/tools/doubleSpinBox.h \
	$$PWD/widgetsEdit/tools/abstractScrollArea.h \
	$$PWD/widgetsEdit/tools/abstractSpinBox.h \
	$$PWD/widgetsEdit/tools/abstractButton.h \
	$$PWD/widgetsEdit/tools/spacer.h \
	$$PWD/widgetsEdit/tools/layoutHelpers/layoutHelperBase.h \
	$$PWD/widgetsEdit/tools/layoutHelpers/gridLayoutHelper.h \
	$$PWD/widgetsEdit/tools/layoutHelpers/linearLayoutHelper.h \
	$$PWD/widgetsEdit/tools/layoutHelpers/layoutTypes.h \
	$$PWD/widgetsEdit/tools/layoutHelpers/layoutHelperFactory.h \
	$$PWD/widgetsEdit/tools/trigger.h \
	$$PWD/widgetsEdit/tools/triggerWidget.h \
	$$PWD/widgetsEdit/tools/propertyEditor.h \
	$$PWD/widgetsEdit/propertyBinding/propertyBinder.h \
	$$PWD/elementEditor.h \
	$$PWD/widgetsEdit/propertyBinding/propertyProxyBase.h \
	$$PWD/widgetsEdit/private/outerBindingsDialog.h \
	$$PWD/widgetsEdit/propertyBinding/metaPropertyBinding.h \
	$$PWD/widgetsEdit/tools/labelTool.h

SOURCES += \
	$$PWD/common/startPage.cpp \
	$$PWD/common/templateDocumentBuilder.cpp \
	$$PWD/common/controlButtons.cpp \
	$$PWD/shapeEdit/shapeEdit.cpp \
	$$PWD/shapeEdit/scene.cpp \
	$$PWD/shapeEdit/arch.cpp \
	$$PWD/shapeEdit/line.cpp \
	$$PWD/shapeEdit/item.cpp \
	$$PWD/shapeEdit/ellipse.cpp \
	$$PWD/shapeEdit/rectangle.cpp \
	$$PWD/shapeEdit/text.cpp \
	$$PWD/shapeEdit/pointPort.cpp \
	$$PWD/shapeEdit/linePort.cpp \
	$$PWD/shapeEdit/xmlLoader.cpp \
	$$PWD/shapeEdit/stylus.cpp \
	$$PWD/shapeEdit/colorListEditor.cpp \
	$$PWD/shapeEdit/path.cpp \
	$$PWD/shapeEdit/curve.cpp \
	$$PWD/shapeEdit/view.cpp \
	$$PWD/shapeEdit/textPicture.cpp \
	$$PWD/shapeEdit/image.cpp \
	$$PWD/shapeEdit/visibilityConditionsDialog.cpp \
	$$PWD/shapeEdit/visibilityValueWidget.cpp \
	$$PWD/widgetsEdit/widgetsEditor.cpp \
	$$PWD/widgetsEdit/private/toolFactory.cpp \
	$$PWD/widgetsEdit/private/toolList.cpp \
	$$PWD/widgetsEdit/private/layoutButton.cpp \
	$$PWD/widgetsEdit/private/toolController.cpp \
	$$PWD/widgetsEdit/private/layoutButtons.cpp \
	$$PWD/widgetsEdit/private/editorScene.cpp \
	$$PWD/widgetsEdit/private/propertyBrowserController.cpp \
	$$PWD/widgetsEdit/tools/propertyManager.cpp \
	$$PWD/widgetsEdit/tools/property.cpp \
	$$PWD/widgetsEdit/tools/tool.cpp \
	$$PWD/widgetsEdit/tools/layoutTool.cpp \
	$$PWD/widgetsEdit/tools/root.cpp \
	$$PWD/widgetsEdit/tools/rootWidget.cpp \
	$$PWD/widgetsEdit/tools/checkBox.cpp \
	$$PWD/widgetsEdit/tools/comboBox.cpp \
	$$PWD/widgetsEdit/tools/groupBox.cpp \
	$$PWD/widgetsEdit/tools/pushButton.cpp \
	$$PWD/widgetsEdit/tools/radioButton.cpp \
	$$PWD/widgetsEdit/tools/scrollArea.cpp \
	$$PWD/widgetsEdit/tools/frame.cpp \
	$$PWD/widgetsEdit/tools/widget.cpp \
	$$PWD/widgetsEdit/tools/lineEdit.cpp \
	$$PWD/widgetsEdit/tools/plainTextEdit.cpp \
	$$PWD/widgetsEdit/tools/spinBox.cpp \
	$$PWD/widgetsEdit/tools/doubleSpinBox.cpp \
	$$PWD/widgetsEdit/tools/abstractScrollArea.cpp \
	$$PWD/widgetsEdit/tools/abstractSpinBox.cpp \
	$$PWD/widgetsEdit/tools/abstractButton.cpp \
	$$PWD/widgetsEdit/tools/spacer.cpp \
	$$PWD/widgetsEdit/tools/layoutHelpers/layoutHelperBase.cpp \
	$$PWD/widgetsEdit/tools/layoutHelpers/gridLayoutHelper.cpp \
	$$PWD/widgetsEdit/tools/layoutHelpers/linearLayoutHelper.cpp \
	$$PWD/widgetsEdit/tools/layoutHelpers/layoutHelperFactory.cpp \
	$$PWD/widgetsEdit/tools/trigger.cpp \
	$$PWD/widgetsEdit/tools/triggerWidget.cpp \
	$$PWD/widgetsEdit/tools/propertyEditor.cpp \
	$$PWD/widgetsEdit/propertyBinding/propertyBinder.cpp \
	$$PWD/elementEditor.cpp \
	$$PWD/widgetsEdit/propertyBinding/propertyProxyBase.cpp \
	$$PWD/widgetsEdit/private/outerBindingsDialog.cpp \
	$$PWD/widgetsEdit/propertyBinding/metaPropertyBinding.cpp \
	$$PWD/widgetsEdit/tools/labelTool.cpp

FORMS += \
	$$PWD/shapeEdit/shapeEdit.ui \
	$$PWD/shapeEdit/visibilityConditionsDialog.ui \
	$$PWD/widgetsEdit/widgetsEditor.ui \
	$$PWD/widgetsEdit/private/outerBindongsDialog.ui
