var newDiagram = guiFacade.widget("Action", "actionNew_Diagram");
virtualCursor.moveTo(newDiagram, 1000);
virtualCursor.leftButtonPress(newDiagram);
virtualCursor.leftButtonRelease(newDiagram, 400);
var init = scriptAPI.initialNode();
var mainScene = guiFacade.widget("Scene")
var engF = virtualCursor.dragPaletteElement("qrm:/RobotsMetamodel/RobotsDiagram/EnginesForward", 1000, 150, 275);
var sonar = virtualCursor.dragPaletteElement("qrm:/RobotsMetamodel/RobotsDiagram/WaitForSonarDistance"  , 1000, 250, 275);
var prop = guiFacade.property("Дистанция");
var prop1 = guiFacade.property("Считанное значение");
virtualCursor.moveToRect(prop1, 1000);
var propertyEditor = guiFacade.widget("PropertyEditor");
virtualCursor.leftButtonPress(propertyEditor);
virtualCursor.leftButtonRelease(propertyEditor, 400); 	
var val = guiFacade.widget("ComboBox", "Считанное значение");
virtualCursor.leftButtonPress(val);
virtualCursor.leftButtonRelease(val, 5);
virtualCursor.pickComboBoxItem(val, "меньше", 1000);
virtualCursor.moveToRect(prop, 1000);
virtualCursor.type("50", 1000);
var engB = virtualCursor.dragPaletteElement("qrm:/RobotsMetamodel/RobotsDiagram/EnginesBackward", 2000, 350, 275);
var beep = virtualCursor.dragPaletteElement("qrm:/RobotsMetamodel/RobotsDiagram/Beep", 2000, 450, 275);
var timer = virtualCursor.dragPaletteElement("qrm:/RobotsMetamodel/RobotsDiagram/Timer", 2000, 350, 100);
virtualCursor.drawLink(init, engF, 1000);
virtualCursor.drawLink(engF, sonar, 1000);
virtualCursor.drawLink(sonar, engB, 1000);
virtualCursor.drawLink(engB, beep, 1000);
virtualCursor.drawLink(beep, timer, 1000);
virtualCursor.drawLink(timer, engF, 1000);
var sensors = guiFacade.widget("ComboBox", "port1ComboBox");
virtualCursor.moveTo(sensors, 1000);
virtualCursor.leftButtonPress(sensors);
virtualCursor.leftButtonRelease(sensors);
virtualCursor.pickComboBoxItem(sensors, "Сенсор расстояния", 1000);
var open2DModel = guiFacade.widget("2dModel", "open");
virtualCursor.moveTo(open2DModel, 1000);
virtualCursor.leftButtonPress(open2DModel);
var widget = robotsGuiFacade.d2ModelWidget();
virtualCursor.leftButtonRelease(open2DModel);
scriptAPI.changeWindow(widget);
var wall = robotsGuiFacade.widget("PushButton", "wallButton");
virtualCursor.moveTo(wall, 1000);
virtualCursor.leftButtonPress(wall);
virtualCursor.leftButtonRelease(wall);
var scene = robotsGuiFacade.d2ModelScene();
virtualCursor.sceneMoveTo(scene, 1000, 400, 100);
virtualCursor.rightButtonPress(scene);
virtualCursor.sceneMoveTo(scene, 1000, 400, 400);
virtualCursor.rightButtonRelease(scene);
var run = robotsGuiFacade.widget("PushButton", "runButton");
virtualCursor.moveTo(run, 1000);
virtualCursor.leftButtonPress(run);
virtualCursor.leftButtonRelease(run);