######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 6 00:46:54 2007
######################################################################

QT += xml
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += parser.h
SOURCES += main.cpp parser.cpp
