######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 6 00:46:54 2007
######################################################################

QT += xml
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += generator.h entity.h
SOURCES += main.cpp generator.cpp entity.cpp
