ARRAY8 a1@@RANDOM_ID_1@@ 8 // [1 69 point P K D] setup 1 1
ARRAY(CREATE8, 8, a1@@RANDOM_ID_1@@)
ARRAY_WRITE(a1@@RANDOM_ID_1@@, 0, 1)
ARRAY_WRITE(a1@@RANDOM_ID_1@@, 1, 69)
ARRAY_WRITE(a1@@RANDOM_ID_1@@, 2, @@SET_POINT@@)
ARRAY_WRITE(a1@@RANDOM_ID_1@@, 3, @@P@@)
ARRAY_WRITE(a1@@RANDOM_ID_1@@, 4, @@K@@)
ARRAY_WRITE(a1@@RANDOM_ID_1@@, 5, @@D@@)

ARRAY8 a2@@RANDOM_ID_2@@ 8 // [1 97 KPF KIF KDF 0] setup 1 1
ARRAY(CREATE8, 8, a2@@RANDOM_ID_2@@)
ARRAY_WRITE(a2@@RANDOM_ID_2@@, 0, 1)
ARRAY_WRITE(a2@@RANDOM_ID_2@@, 1, 97)
ARRAY_WRITE(a2@@RANDOM_ID_2@@, 2, @@KPF@@)
ARRAY_WRITE(a2@@RANDOM_ID_2@@, 3, @@KIF@@)
ARRAY_WRITE(a2@@RANDOM_ID_2@@, 4, @@KDF@@)

DATA8 res@@RANDOM_ID_6@@
ARRAY8 answer@@RANDOM_ID_3@@ 4
ARRAY(CREATE8, 4, answer@@RANDOM_ID_3@@)

INPUT_DEVICE(SETUP, 0, @@PORT@@, 1, 1, 6, @a1@@RANDOM_ID_1@@, 1, @answer@@RANDOM_ID_3@@)
ARRAY_READ(answer@@RANDOM_ID_3@@, 0, res@@RANDOM_ID_6@@)
JR_EQ8(res@@RANDOM_ID_6@@, 0, m2@@RANDOM_ID_4@@)

INPUT_DEVICE(SETUP, 0, @@PORT@@, 1, 1, 6, @a1@@RANDOM_ID_1@@, 1, @answer@@RANDOM_ID_3@@)
ARRAY_READ(answer@@RANDOM_ID_3@@, 0, res@@RANDOM_ID_6@@)
JR_EQ8(res@@RANDOM_ID_6@@, 0, m2@@RANDOM_ID_4@@)
INPUT_DEVICE(SETUP, 0, @@PORT@@, 1, 1, 6, @a1@@RANDOM_ID_1@@, 0, @answer@@RANDOM_ID_3@@)

m2@@RANDOM_ID_4@@:
INPUT_DEVICE(SETUP, 0, @@PORT@@, 1, 1, 5, @a2@@RANDOM_ID_2@@, 1, @answer@@RANDOM_ID_3@@)
ARRAY_READ(answer@@RANDOM_ID_3@@, 0, res@@RANDOM_ID_6@@)
JR_EQ8(res@@RANDOM_ID_6@@, 0, exit@@RANDOM_ID_5@@)

INPUT_DEVICE(SETUP, 0, @@PORT@@, 1, 1, 5, @a2@@RANDOM_ID_2@@, 1, @answer@@RANDOM_ID_3@@)
ARRAY_READ(answer@@RANDOM_ID_3@@, 0, res@@RANDOM_ID_6@@)
JR_EQ8(res@@RANDOM_ID_6@@, 0, exit@@RANDOM_ID_5@@)
INPUT_DEVICE(SETUP, 0, @@PORT@@, 1, 1, 5, @a2@@RANDOM_ID_2@@, 0, @answer@@RANDOM_ID_3@@)

exit@@RANDOM_ID_5@@:

ARRAY(DELETE, a1@@RANDOM_ID_1@@)
ARRAY(DELETE, a2@@RANDOM_ID_2@@)
ARRAY(DELETE, answer@@RANDOM_ID_4@@)