/** \file
 *  This C header file was generated by $ANTLR version 3.2 Sep 23, 2009 12:02:23
 *
 *     -  From the grammar source file : D:\\Diploma\\temp\\qrgui\\generators\\java\\activity.g
 *     -                            On : 2010-05-13 19:02:15
 *     -                 for the lexer : activityLexerLexer *
 * Editing it, at least manually, is not wise. 
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
 * The lexer activityLexer has the callable functions (rules) shown below,
 * which will invoke the code for the associated rule in the source grammar
 * assuming that the input stream is pointing to a token/text stream that could begin
 * this rule.
 * 
 * For instance if you call the first (topmost) rule in a parser grammar, you will
 * get the results of a full parse, but calling a rule half way through the grammar will
 * allow you to pass part of a full token stream to the parser, such as for syntax checking
 * in editors and so on.
 *
 * The parser entry points are called indirectly (by function pointer to function) via
 * a parser context typedef pactivityLexer, which is returned from a call to activityLexerNew().
 *
 * As this is a generated lexer, it is unlikely you will call it 'manually'. However
 * the methods are provided anyway.
 * * The methods in pactivityLexer are  as follows:
 *
 *  -  void      pactivityLexer->T__24(pactivityLexer)
 *  -  void      pactivityLexer->T__25(pactivityLexer)
 *  -  void      pactivityLexer->T__26(pactivityLexer)
 *  -  void      pactivityLexer->T__27(pactivityLexer)
 *  -  void      pactivityLexer->T__28(pactivityLexer)
 *  -  void      pactivityLexer->T__29(pactivityLexer)
 *  -  void      pactivityLexer->T__30(pactivityLexer)
 *  -  void      pactivityLexer->T__31(pactivityLexer)
 *  -  void      pactivityLexer->T__32(pactivityLexer)
 *  -  void      pactivityLexer->T__33(pactivityLexer)
 *  -  void      pactivityLexer->T__34(pactivityLexer)
 *  -  void      pactivityLexer->T__35(pactivityLexer)
 *  -  void      pactivityLexer->T__36(pactivityLexer)
 *  -  void      pactivityLexer->T__37(pactivityLexer)
 *  -  void      pactivityLexer->T__38(pactivityLexer)
 *  -  void      pactivityLexer->T__39(pactivityLexer)
 *  -  void      pactivityLexer->T__40(pactivityLexer)
 *  -  void      pactivityLexer->T__41(pactivityLexer)
 *  -  void      pactivityLexer->T__42(pactivityLexer)
 *  -  void      pactivityLexer->T__43(pactivityLexer)
 *  -  void      pactivityLexer->T__44(pactivityLexer)
 *  -  void      pactivityLexer->T__45(pactivityLexer)
 *  -  void      pactivityLexer->T__46(pactivityLexer)
 *  -  void      pactivityLexer->T__47(pactivityLexer)
 *  -  void      pactivityLexer->T__48(pactivityLexer)
 *  -  void      pactivityLexer->T__49(pactivityLexer)
 *  -  void      pactivityLexer->T__50(pactivityLexer)
 *  -  void      pactivityLexer->T__51(pactivityLexer)
 *  -  void      pactivityLexer->T__52(pactivityLexer)
 *  -  void      pactivityLexer->T__53(pactivityLexer)
 *  -  void      pactivityLexer->T__54(pactivityLexer)
 *  -  void      pactivityLexer->T__55(pactivityLexer)
 *  -  void      pactivityLexer->T__56(pactivityLexer)
 *  -  void      pactivityLexer->T__57(pactivityLexer)
 *  -  void      pactivityLexer->T__58(pactivityLexer)
 *  -  void      pactivityLexer->T__59(pactivityLexer)
 *  -  void      pactivityLexer->T__60(pactivityLexer)
 *  -  void      pactivityLexer->T__61(pactivityLexer)
 *  -  void      pactivityLexer->T__62(pactivityLexer)
 *  -  void      pactivityLexer->T__63(pactivityLexer)
 *  -  void      pactivityLexer->T__64(pactivityLexer)
 *  -  void      pactivityLexer->T__65(pactivityLexer)
 *  -  void      pactivityLexer->T__66(pactivityLexer)
 *  -  void      pactivityLexer->T__67(pactivityLexer)
 *  -  void      pactivityLexer->T__68(pactivityLexer)
 *  -  void      pactivityLexer->T__69(pactivityLexer)
 *  -  void      pactivityLexer->T__70(pactivityLexer)
 *  -  void      pactivityLexer->T__71(pactivityLexer)
 *  -  void      pactivityLexer->T__72(pactivityLexer)
 *  -  void      pactivityLexer->T__73(pactivityLexer)
 *  -  void      pactivityLexer->T__74(pactivityLexer)
 *  -  void      pactivityLexer->T__75(pactivityLexer)
 *  -  void      pactivityLexer->T__76(pactivityLexer)
 *  -  void      pactivityLexer->T__77(pactivityLexer)
 *  -  void      pactivityLexer->T__78(pactivityLexer)
 *  -  void      pactivityLexer->T__79(pactivityLexer)
 *  -  void      pactivityLexer->T__80(pactivityLexer)
 *  -  void      pactivityLexer->T__81(pactivityLexer)
 *  -  void      pactivityLexer->T__82(pactivityLexer)
 *  -  void      pactivityLexer->T__83(pactivityLexer)
 *  -  void      pactivityLexer->T__84(pactivityLexer)
 *  -  void      pactivityLexer->T__85(pactivityLexer)
 *  -  void      pactivityLexer->T__86(pactivityLexer)
 *  -  void      pactivityLexer->T__87(pactivityLexer)
 *  -  void      pactivityLexer->T__88(pactivityLexer)
 *  -  void      pactivityLexer->T__89(pactivityLexer)
 *  -  void      pactivityLexer->T__90(pactivityLexer)
 *  -  void      pactivityLexer->T__91(pactivityLexer)
 *  -  void      pactivityLexer->T__92(pactivityLexer)
 *  -  void      pactivityLexer->T__93(pactivityLexer)
 *  -  void      pactivityLexer->T__94(pactivityLexer)
 *  -  void      pactivityLexer->T__95(pactivityLexer)
 *  -  void      pactivityLexer->T__96(pactivityLexer)
 *  -  void      pactivityLexer->T__97(pactivityLexer)
 *  -  void      pactivityLexer->T__98(pactivityLexer)
 *  -  void      pactivityLexer->T__99(pactivityLexer)
 *  -  void      pactivityLexer->T__100(pactivityLexer)
 *  -  void      pactivityLexer->T__101(pactivityLexer)
 *  -  void      pactivityLexer->T__102(pactivityLexer)
 *  -  void      pactivityLexer->T__103(pactivityLexer)
 *  -  void      pactivityLexer->T__104(pactivityLexer)
 *  -  void      pactivityLexer->T__105(pactivityLexer)
 *  -  void      pactivityLexer->T__106(pactivityLexer)
 *  -  void      pactivityLexer->T__107(pactivityLexer)
 *  -  void      pactivityLexer->T__108(pactivityLexer)
 *  -  void      pactivityLexer->T__109(pactivityLexer)
 *  -  void      pactivityLexer->T__110(pactivityLexer)
 *  -  void      pactivityLexer->HexLiteral(pactivityLexer)
 *  -  void      pactivityLexer->DecimalLiteral(pactivityLexer)
 *  -  void      pactivityLexer->OctalLiteral(pactivityLexer)
 *  -  void      pactivityLexer->HexDigit(pactivityLexer)
 *  -  void      pactivityLexer->IntegerTypeSuffix(pactivityLexer)
 *  -  void      pactivityLexer->FloatingPointLiteral(pactivityLexer)
 *  -  void      pactivityLexer->Exponent(pactivityLexer)
 *  -  void      pactivityLexer->FloatTypeSuffix(pactivityLexer)
 *  -  void      pactivityLexer->CharacterLiteral(pactivityLexer)
 *  -  void      pactivityLexer->StringLiteral(pactivityLexer)
 *  -  void      pactivityLexer->EscapeSequence(pactivityLexer)
 *  -  void      pactivityLexer->OctalEscape(pactivityLexer)
 *  -  void      pactivityLexer->UnicodeEscape(pactivityLexer)
 *  -  void      pactivityLexer->ENUM(pactivityLexer)
 *  -  void      pactivityLexer->Identifier(pactivityLexer)
 *  -  void      pactivityLexer->Letter(pactivityLexer)
 *  -  void      pactivityLexer->JavaIDDigit(pactivityLexer)
 *  -  void      pactivityLexer->WS(pactivityLexer)
 *  -  void      pactivityLexer->COMMENT(pactivityLexer)
 *  -  void      pactivityLexer->LINE_COMMENT(pactivityLexer)
 *  -  void      pactivityLexer->Tokens(pactivityLexer)
 *
 * The return type for any particular rule is of course determined by the source
 * grammar file.
 */
// [The "BSD licence"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef	_activityLexer_H
#define _activityLexer_H
/* =============================================================================
 * Standard antlr3 C runtime definitions
 */
#include    <antlr3.h>

/* End of standard antlr 3 runtime definitions
 * =============================================================================
 */
 
#ifdef __cplusplus
extern "C" {
#endif

// Forward declare the context typedef so that we can use it before it is
// properly defined. Delegators and delegates (from import statements) are
// interdependent and their context structures contain pointers to each other
// C only allows such things to be declared if you pre-declare the typedef.
//
typedef struct activityLexer_Ctx_struct activityLexer, * pactivityLexer;



#define	ANTLR3_INLINE_INPUT_ASCII


#ifdef	ANTLR3_WINDOWS
// Disable: Unreferenced parameter,							- Rules with parameters that are not used
//          constant conditional,							- ANTLR realizes that a prediction is always true (synpred usually)
//          initialized but unused variable					- tree rewrite variables declared but not needed
//          Unreferenced local variable						- lexer rule declares but does not always use _type
//          potentially unitialized variable used			- retval always returned from a rule 
//			unreferenced local function has been removed	- susually getTokenNames or freeScope, they can go without warnigns
//
// These are only really displayed at warning level /W4 but that is the code ideal I am aiming at
// and the codegen must generate some of these warnings by necessity, apart from 4100, which is
// usually generated when a parser rule is given a parameter that it does not use. Mostly though
// this is a matter of orthogonality hence I disable that one.
//
#pragma warning( disable : 4100 )
#pragma warning( disable : 4101 )
#pragma warning( disable : 4127 )
#pragma warning( disable : 4189 )
#pragma warning( disable : 4505 )
#pragma warning( disable : 4701 )
#endif

/** Context tracking structure for activityLexer
 */
struct activityLexer_Ctx_struct
{
    /** Built in ANTLR3 context tracker contains all the generic elements
     *  required for context tracking.
     */
    pANTLR3_LEXER    pLexer;


     void (*mT__24)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__25)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__26)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__27)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__28)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__29)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__30)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__31)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__32)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__33)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__34)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__35)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__36)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__37)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__38)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__39)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__40)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__41)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__42)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__43)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__44)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__45)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__46)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__47)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__48)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__49)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__50)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__51)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__52)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__53)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__54)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__55)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__56)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__57)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__58)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__59)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__60)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__61)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__62)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__63)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__64)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__65)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__66)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__67)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__68)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__69)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__70)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__71)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__72)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__73)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__74)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__75)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__76)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__77)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__78)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__79)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__80)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__81)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__82)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__83)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__84)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__85)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__86)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__87)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__88)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__89)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__90)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__91)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__92)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__93)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__94)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__95)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__96)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__97)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__98)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__99)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__100)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__101)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__102)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__103)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__104)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__105)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__106)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__107)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__108)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__109)	(struct activityLexer_Ctx_struct * ctx);
     void (*mT__110)	(struct activityLexer_Ctx_struct * ctx);
     void (*mHexLiteral)	(struct activityLexer_Ctx_struct * ctx);
     void (*mDecimalLiteral)	(struct activityLexer_Ctx_struct * ctx);
     void (*mOctalLiteral)	(struct activityLexer_Ctx_struct * ctx);
     void (*mHexDigit)	(struct activityLexer_Ctx_struct * ctx);
     void (*mIntegerTypeSuffix)	(struct activityLexer_Ctx_struct * ctx);
     void (*mFloatingPointLiteral)	(struct activityLexer_Ctx_struct * ctx);
     void (*mExponent)	(struct activityLexer_Ctx_struct * ctx);
     void (*mFloatTypeSuffix)	(struct activityLexer_Ctx_struct * ctx);
     void (*mCharacterLiteral)	(struct activityLexer_Ctx_struct * ctx);
     void (*mStringLiteral)	(struct activityLexer_Ctx_struct * ctx);
     void (*mEscapeSequence)	(struct activityLexer_Ctx_struct * ctx);
     void (*mOctalEscape)	(struct activityLexer_Ctx_struct * ctx);
     void (*mUnicodeEscape)	(struct activityLexer_Ctx_struct * ctx);
     void (*mENUM)	(struct activityLexer_Ctx_struct * ctx);
     void (*mIdentifier)	(struct activityLexer_Ctx_struct * ctx);
     void (*mLetter)	(struct activityLexer_Ctx_struct * ctx);
     void (*mJavaIDDigit)	(struct activityLexer_Ctx_struct * ctx);
     void (*mWS)	(struct activityLexer_Ctx_struct * ctx);
     void (*mCOMMENT)	(struct activityLexer_Ctx_struct * ctx);
     void (*mLINE_COMMENT)	(struct activityLexer_Ctx_struct * ctx);
     void (*mTokens)	(struct activityLexer_Ctx_struct * ctx);    const char * (*getGrammarFileName)();
    void	    (*free)   (struct activityLexer_Ctx_struct * ctx);
        
};

// Function protoypes for the constructor functions that external translation units
// such as delegators and delegates may wish to call.
//
ANTLR3_API pactivityLexer activityLexerNew         (pANTLR3_INPUT_STREAM instream);
ANTLR3_API pactivityLexer activityLexerNewSSD      (pANTLR3_INPUT_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state);

/** Symbolic definitions of all the tokens that the lexer will work with.
 * \{
 *
 * Antlr will define EOF, but we can't use that as it it is too common in
 * in C header files and that would be confusing. There is no way to filter this out at the moment
 * so we just undef it here for now. That isn't the value we get back from C recognizers
 * anyway. We are looking for ANTLR3_TOKEN_EOF.
 */
#ifdef	EOF
#undef	EOF
#endif
#ifdef	Tokens
#undef	Tokens
#endif 
#define T__29      29
#define T__28      28
#define T__27      27
#define T__26      26
#define FloatTypeSuffix      15
#define T__25      25
#define OctalLiteral      10
#define T__24      24
#define EOF      -1
#define Identifier      4
#define T__93      93
#define T__94      94
#define T__91      91
#define T__92      92
#define T__90      90
#define COMMENT      22
#define T__99      99
#define T__98      98
#define T__97      97
#define T__96      96
#define T__95      95
#define T__80      80
#define T__81      81
#define T__82      82
#define T__83      83
#define LINE_COMMENT      23
#define IntegerTypeSuffix      13
#define T__85      85
#define T__84      84
#define T__87      87
#define T__86      86
#define T__89      89
#define T__88      88
#define T__71      71
#define WS      21
#define T__72      72
#define T__70      70
#define FloatingPointLiteral      6
#define JavaIDDigit      20
#define T__76      76
#define T__75      75
#define T__74      74
#define Letter      19
#define EscapeSequence      16
#define T__73      73
#define T__79      79
#define T__78      78
#define T__77      77
#define T__68      68
#define T__69      69
#define T__66      66
#define T__67      67
#define T__64      64
#define T__65      65
#define T__62      62
#define T__63      63
#define CharacterLiteral      7
#define Exponent      14
#define T__61      61
#define T__60      60
#define HexDigit      12
#define T__55      55
#define T__56      56
#define T__57      57
#define T__58      58
#define T__51      51
#define T__52      52
#define T__53      53
#define T__54      54
#define T__107      107
#define T__108      108
#define T__109      109
#define T__59      59
#define T__103      103
#define T__104      104
#define T__105      105
#define T__106      106
#define T__110      110
#define T__50      50
#define T__42      42
#define HexLiteral      9
#define T__43      43
#define T__40      40
#define T__41      41
#define T__46      46
#define T__47      47
#define T__44      44
#define T__45      45
#define T__48      48
#define T__49      49
#define T__102      102
#define T__101      101
#define T__100      100
#define DecimalLiteral      11
#define StringLiteral      8
#define T__30      30
#define T__31      31
#define T__32      32
#define T__33      33
#define T__34      34
#define ENUM      5
#define T__35      35
#define T__36      36
#define T__37      37
#define T__38      38
#define T__39      39
#define UnicodeEscape      17
#define OctalEscape      18
#ifdef	EOF
#undef	EOF
#define	EOF	ANTLR3_TOKEN_EOF
#endif

#ifndef TOKENSOURCE
#define TOKENSOURCE(lxr) lxr->pLexer->rec->state->tokSource
#endif

/* End of token definitions for activityLexer
 * =============================================================================
 */
/** \} */

#ifdef __cplusplus
}
#endif

#endif

/* END - Note:Keep extra line feed to satisfy UNIX systems */
