######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 24 13:25:26 2010
######################################################################

TEMPLATE = app
TARGET = qrgl
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += \
	../qrrepo/repoApi.h #\
	#../qrgui/kernel/ids.h

SOURCES += main.cpp #\
	#../qrgui/kernel/ids.cpp

LIBS += -L../qrgui -lqrrepo

QMAKE_LFLAGS="-Wl,-O1,-rpath,$(PWD)/../qrgui"
