long cfExp(float *rpafIn,int riStrideInp,float *rpafOut,int riStrideOut,int riLen);
long vfSum(float *gfpIn,int giStrideInp,float *gfpOut,int len);
long cfMatrixDeterm(_c_float *rpacfIn,int riN,_c_float *rpacfOut);
long vfDiv40(float *rpafIn1,int riStrideInp1,float *rpafIn2,int riStrideInp2,float *rpafOut,int riStrideOut,int riLen);
long fMatrixTrace(float *rpafIn,int riDim,float *rpafOut);
long vfMean(float *gfpIn,int giStrideInp,float *gfpOut,int len);
long cfMagn(float *rpafIn,int riStrideInp,float *rpafOut,int riStrideOut,int riLen);
long vfCosh(float *rpafIn,int riStrideInp,float *rpafOut,int riStrideOut,int riLen);
long vfConv(float *rpafInX,float *rpafInCoeffH,float *rpafOut,int riVecLen,int riFilterLen,int riTransient);
long fLPC2Cepstr(float *rpafLPC,float *rpafCC,int riLPCLen,int riCCLen);
long cfMatrixTrace(_c_float *rpacfIn,int riDim,_c_float *rpacfOut);
long vfMax(float *rpavfIn,int riStrideInp,float *rpavfOut,int riLen);
long fFIRnlms(float *rpafInX,float *rpafKerCoeffH,float *rpafRefOut,float *rpafDelayBuff,int riSampleLen,int riKernelLen,float rfAdapCoeff);
long vfClip(float *rpafX, int riStrideX,float *rpafY,int riStrideY,float *rfClipUp,float *rfClipDown,int riLen);
long vfAcos(float *rpafIn,int riStrideInp,float *rpafOut,int riStrideOut,int riLen);
long vfTan(float *rpafIn,int riStrideInp,float *rpafOut,int riStrideOut,int riLen) ;
long vfFIRnlms(float *rpafInX,float *rpafKerCoeffH,float *rpafRefOut,float *rpafDelayBuff,int riSampleLen,int riKernelLen,float rfAdapCoeff);
long cfDot(float *rfpaIn1,int riStrideInp1,float *rfpaIn2,int riStrideInp2,float *rfpaOut,int riLen);
long cfMatrixByVectsMul(_c_float *rpacfIn1,int riRow,int riCol,_c_float *rpacfIn2,_c_float *rpafOut,int riVnum);
long cfMatrixByVectsMul_even(_c_float *rpacfIn1,int riRow,int riCol,_c_float *rpacfIn2,_c_float *rpafOut,int riVnum);
long cfMatrixByVectsMul_odd(_c_float *rpacfIn1,int riRow,int riCol,_c_float *rpacfIn2,_c_float *rpafOut,int riVnum);
long vfSub(float *gfpIn1,int giStrideInp1,float *gfpIn2,int giStrideInp2,float *gfpOut,int giStrideOut,int giLen);
long cfMatrix8x8ByVectsMul(_c_float *rpafIn1,_c_float *rpafIn2,_c_float *rpafOut,int riVnum);
long cfMoveScaleOffset (float *gfpIn,int giStrideInp,float *gfpOut,int giStrideOut,float *gfpScale,float *gfpOffset,int giLen);
long fMatrixMul(float *rpfIn1,int riRow_m1,int riCr_m1m2,float *rpfIn2,int riCol_m2,float *rpfOut);//this implementation works for all inputs
long fMatrixMul_even(float *rpfIn1,int riRow_m1,int riCr_m1m2,float *rpfIn2,int riCol_m2,float *rpfOut_opt);//this is called when the first matrix has even
                                                        //columns and the second matrix has odd columns
long fMatrixMul_even_vf(float *rpfIn1,int riRow_m1,int riCr_m1m2,float *rpfIn2,int riCol_m2,float *rpfOut_opt);//this is called when the first matrix has even
                                                        //columns and the second matrix has even columns.
														//Makes use of _v_float data types.
long fMatrixMul_odd(float *rpfIn1,int riRow_m1,int riCr_m1m2,float *rpfIn2,int riCol_m2,float *rpfOut_opt);//This is called when the first matrix has odd columns.
long fLevinson(float *rpafInAutoCorR,float *rpafLPCOut,float *rpfScalarOut,int riCoeffNum);
long vfMoveScaleOffset(float *gfpIn,int giStrideInp,float *gfpOut,int giStrideOut,float *gfpScale,float *gfpOffset,int giLen);
long fConv2d(float *rpafInA,int riRowLenA,int riColLenA,float *rpafInKernelH,float *rpafOut,int riKOrder);
long vfRMS(float *rpafIn,int riStrideInp,float *rpafOut,int riLen);
long vfMaxAndIndex(float *rpafIn,int riStrideInp,float *rpafMax,long *rpalMaxIdx,int riLen);
long vfExp(float *rpafIn,int riStrideInp,float *rpafOut,int riStrideOut,int riLen);
long vfTanh(float *rpafIn,int riStrideInp,float *rpafOut,int riStrideOut,int riLen);
long fMean(float *gfpIn,int giStrideInp,float *gfpOut,int len);
long cfVectByMatrixMul(_c_float *rpacfIn1,_c_float *rpacfIn2,int riRow,int riCol,_c_float *rpacfOut);
long cfVectByMatrixMul_even(_c_float *rpacfIn1,_c_float *rpacfIn2,int riRow,int riCol,_c_float *rpacfOut);
long cfVectByMatrixMul_odd(_c_float *rpacfIn1,_c_float *rpacfIn2,int riRow,int riCol,_c_float *rpacfOut);
long cfMatrix3x3ByVectsMul(_c_float *rpafIn1,_c_float *rpafIn2,_c_float *rpafOut,int rivnum);
long vfXcorr(float *rpafX,int riStrideX,float *rpafY,int riStrideY,float *rpafZ,int riStrideZ,int riLen,int riNcoeff);
long vfAdd(float *gfpIn1,int giStrideInp1,float *gfpIn2,int giStrideInp2,float *gfpOut,int giStrideOut,int giLen);
long vfLog(float *rpafIn,int riStrideInp,float *rpafOut,int riStrideOut,float rfBaseConversion,int riLen);
long cfMatrixChol(_c_float *rpacfIn,_c_float *rpacfOut_1,_c_float *rpacfOut_2,int riN);
long fMatrixDeterm(float *rpafIn,int riN,float *rpafOut);
long vfDot(float *rfpaIn1,int riStrideInp1,float *rfpaIn2,int riStrideInp2,float *rfpaOut,int riLen);
long vfAcosh(float *rpafIn,int riStrideInp,float *rpafOut,int riStrideOut,int riLen);
long cfMulAdd(float *rpafIn1,int riStrideInp1,float *rpafIn2,int riStrideInp2,float *rpafIn3,int riStrideInp3,float *rpfOut,int riStrideOut,int riLen);
long cfDist(float *rpafIn1,int giStrideInp1,float *rpafIn2,int giStrideInp2,float *rpafOut,int giStrideOut,int riLen);
long vfExp10(float *rpafIn,int riStrideInp,float *rpafOut,int riStrideOut,
		     int riLen);
long fMatrixAdd(float *rpacfIn1,float *rpafIn2,int riRows,int riCols,float *rpafOut);
long cfMatrix2Determ(float *rpafIn,float *rpafOut);
long cfConjScaleOffset(float *gfpIn,int giStrideInp,float *gfpOut,int giStrideOut,float *gfpScale,float *gfpOffset,int giLen);
long vfFixScaleOffset(float *gfpIn1,int giStrideInp,long *glpOut,int giStrideOut,float *gfpScale,float *gfpOffset,int giLen);
long vfBubbleSort(float *rpafIn,int riStrideInp,int riLen);
long vfCos(float *rpafIn,int riStrideInp,float *rpafOut,int riStrideOut,int riLen);
long vfDiv32(float *rpafIn1,int riStrideInp1,float *rpafIn2,int riStrideInp2,float *rpafOut,int riStrideOut,int riLen);
long cfXcorr(float *rpafX,int riStrideX,float *rpafY,int riStrideY,float *rpafZ,int riStrideZ,int riLen,int riNcoeff);
long cfMulConj(float *gfpIn1,int giStrideInp1,float *gfpIn2,int giStrideInp2,float *gfpOut,int giStrideOut,int len);
long vlShift(long *rpalIn,int riStrideIn,long *rpalOut,int riStrideOut,long rlLShift,long rlRShift,int riLen);
long cfLastStage(float *rpafInX1,float *rpafInX2,float *rpafInW,float *rpafOutY1,float *rpafOutY2,int riButterFlyNum);
long fConv(float *rpafInX,float *rpafInCoeffH,float *rpafOut,int riVecLen,int riFilterLen,int riTransient);
long vlShand(long *rpalIn,int riStrideIn,long *rpalOut,int riStrideOut,long rlLShift,long rlRShift,long rlLMask,long rlRMask,int riLen);
long vfQuickSort(float *rpafIn,int riStrideInp,int riStart,int riEnd);
long vfSinh(float *rpafIn,int riStrideInp,float *rpafOut,int riStrideOut,int riLen);
long vfLog_Base(float *rpafIn,int riStrideInp,float *rpafOut,int riStrideOut,long rlBaseConv,int riLen);
long fMatrixInvert(float *rpafIn,int riN,float *rpafOut);
long vfSin(float *rpafIn,int riStrideInp,float *rpafOut,int riStrideOut,int riLen);
long vlAdd(long *glpIn1,int giStrideInp1,long *glpIn2,int giStrideInp2,long *glpOut,int giStrideOut,int giLen);
long cfConv2d(_c_float *rpafInA,int riRowLenA,int riColLenA,_c_float *rpafInKernelH,_c_float *rpafOut,int riKOrder);
long fSum(float *gfpIn,int giStrideInp,float *gfpOut,int len);
long cfMul(float *gfpIn1,int giStrideInp1,float *gfpIn2,int giStrideInp2,float *gfpOut,int giStrideOut,int len);
long vfMulAdd(float *rpafIn1,int riStrideInp1,float *rpafIn2,int riStrideInp2,float *rpafIn3,int riStrideInp3,float *rpfOut,int riStrideOut,int riLen);
long cfMatrixMul(_c_float *rpcfIn1,int riRow_m1,int riCr_m1m2,_c_float *rpcfIn2,int riCol_m2,_c_float *rpcfOut);
long cfMatrixMul_even(_c_float *rpcfIn1,int riRow_m1,int riCr_m1m2,_c_float *rpcfIn2,int riCol_m2,_c_float *rpcfOut);
long cfMatrixMul_odd(_c_float *rpcfIn1,int riRow_m1,int riCr_m1m2,_c_float *rpcfIn2,int riCol_m2,_c_float *rpcfOut);
long vlToFloatScaleOffset(long *glpIn1,int giStrideInp,float *gfpOut,int giStrideOut,float *gfpScale,float *gfpOffset,int giLen);
long vfMul(float *rpafIn1,int riStrideInp1,float *rpafIn2,int riStrideInp2,float *rpafOut,int riStrideOut,int riLen);
long fMatrixByVectsMul(float *rpacfIn1,int riRow,int riCol,float *rpacfIn2,float *rpafOut,int riVnum);
long fMatrixByVectsMul_even(float *rpacfIn1,int riRow,int riCol,float *rpacfIn2,float *rpafOut,int riVnum);
long vlRotate(long *rpalIn,int riStrideIn,long *rpalOut,int riStrideOut,long rlLShift,long rlRShift,int riLen);
long vfFill(float* gfpIn,float* gfpOut,int giStride_out,int  giLen);
long vfAtanh(float *rpafIn,int riStrideInp,float *rpafOut,int riStrideOut,int riLen);
long vfSqrt(float *rpafIn,int riStrideInp,float *rpafOut,int riStrideOut,int riLen);
long vfAtan2(float *rpafIn,int riStrideInp,float *rpafOut,int riStrideOut,int riLen);
long cfMatrixAdd(_c_float *rpacfIn1,_c_float *rpacfIn2,int riRows,int riCols,_c_float *rpacfOut);
long cfSquareMagn(float *rpafIn,int riStrideInp,float *rpafOut,int riStrideOut,int riLen);
long cfMatrixInvert(_c_float *rpacfIn,int riN,_c_float *rpacfOut);
long vfFixScaleOffsetClip(float *rpafX, int riStrideX,long *rpalY,int riStrideY,float *rfScale,float *rfOffset,float *rfClipUp,float *rfClipDown,int riLen);
long cfMulConjConj(float *gfpIn1,int giStrideInp1,float *gfpIn2,int giStrideInp2,float *gfpOut,int giStrideOut,int len);
long vfVar(float *rpafIn,int riStrideInp,float *rpafOut,float *rpfMean,float *rpafInvlen,int riLen);
long vfAsin(float *rpafIn,int riStrideInp,float *rpafOut,int riStrideOut,int riLen);
long clConjScaleOffset(long *glpIn,int giStrideInp,long *glpOut,int giStrideOut,long *glpScale,long *glpOffset,int giLen);
long clMoveScaleOffset(long *glpIn,int giStrideInp,long *glpOut,int giStrideOut,long *glpScale,long *glpOffset,int giLen);
long fVectByMatrixMul(float *rpacfIn1,float *rpacfIn2,int riRow,int riCol,float *rpacfOut);
long fVectByMatrixMul_even(float *rpacfIn1,float *rpacfIn2,int riRow,int riCol,float *rpacfOut);
long fVectByMatrixMul_odd(float *rpacfIn1,float *rpacfIn2,int riRow,int riCol,float *rpacfOut);
long cfMatrix4x4ByVectsMul(_c_float *rpafIn1,_c_float *rpafIn2,_c_float *rpafOut,int riVnum);
long vfAsinh(float *rpafIn,int riStrideInp,float *rpafOut,int riStrideOut,int riLen);
long cfConv(float *rpafInX,float *rpafInCoeffH,float *rpafOut,int riVecLen,int riFilterLen,int riTransient);
long cfByfDivide(_c_float *rpacfIn1,int riStrideInp1,float *rpacfIn2,int riStrideInp2,_c_float *rpacfOut,int giStrideOut,int riLen);
long vfRand(float *rpafNorm,float *rpafOffset,float *rpafOut,int riStrideOut,int riLen);
long cfMatrix3Determ(float *rpafIn,float *rpafOut);
long fXcorr(float *rpafX,int riStrideX,float *rpafY,int riStrideY,float *rpafZ,int riStrideZ,int riLen,int riNcoeff);
long vlMoveScaleOffset(long *glpIn,int giStrideInp,long *glpOut,int giStrideOut,long *glpScale,long *glpOffset,int giLen);
long fft1024 (_c_float *W, _c_float *input_array, _c_float *temp_array, _c_float *output_array);
long ifft1024 (_c_float *W, _c_float *input_array, _c_float *temp_array, _c_float *output_array);
