/** \file
 *  This C header file was generated by $ANTLR version 3.2 Sep 23, 2009 12:02:23
 *
 *     -  From the grammar source file : D:\\Diploma\\ANTLR\\java.g
 *     -                            On : 2010-04-25 22:26:31
 *     -                 for the lexer : javaLexerLexer *
 * Editing it, at least manually, is not wise. 
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
 * The lexer javaLexer has the callable functions (rules) shown below,
 * which will invoke the code for the associated rule in the source grammar
 * assuming that the input stream is pointing to a token/text stream that could begin
 * this rule.
 * 
 * For instance if you call the first (topmost) rule in a parser grammar, you will
 * get the results of a full parse, but calling a rule half way through the grammar will
 * allow you to pass part of a full token stream to the parser, such as for syntax checking
 * in editors and so on.
 *
 * The parser entry points are called indirectly (by function pointer to function) via
 * a parser context typedef pjavaLexer, which is returned from a call to javaLexerNew().
 *
 * As this is a generated lexer, it is unlikely you will call it 'manually'. However
 * the methods are provided anyway.
 * * The methods in pjavaLexer are  as follows:
 *
 *  -  void      pjavaLexer->T__24(pjavaLexer)
 *  -  void      pjavaLexer->T__25(pjavaLexer)
 *  -  void      pjavaLexer->T__26(pjavaLexer)
 *  -  void      pjavaLexer->T__27(pjavaLexer)
 *  -  void      pjavaLexer->T__28(pjavaLexer)
 *  -  void      pjavaLexer->T__29(pjavaLexer)
 *  -  void      pjavaLexer->T__30(pjavaLexer)
 *  -  void      pjavaLexer->T__31(pjavaLexer)
 *  -  void      pjavaLexer->T__32(pjavaLexer)
 *  -  void      pjavaLexer->T__33(pjavaLexer)
 *  -  void      pjavaLexer->T__34(pjavaLexer)
 *  -  void      pjavaLexer->T__35(pjavaLexer)
 *  -  void      pjavaLexer->T__36(pjavaLexer)
 *  -  void      pjavaLexer->T__37(pjavaLexer)
 *  -  void      pjavaLexer->T__38(pjavaLexer)
 *  -  void      pjavaLexer->T__39(pjavaLexer)
 *  -  void      pjavaLexer->T__40(pjavaLexer)
 *  -  void      pjavaLexer->T__41(pjavaLexer)
 *  -  void      pjavaLexer->T__42(pjavaLexer)
 *  -  void      pjavaLexer->T__43(pjavaLexer)
 *  -  void      pjavaLexer->T__44(pjavaLexer)
 *  -  void      pjavaLexer->T__45(pjavaLexer)
 *  -  void      pjavaLexer->T__46(pjavaLexer)
 *  -  void      pjavaLexer->T__47(pjavaLexer)
 *  -  void      pjavaLexer->T__48(pjavaLexer)
 *  -  void      pjavaLexer->T__49(pjavaLexer)
 *  -  void      pjavaLexer->T__50(pjavaLexer)
 *  -  void      pjavaLexer->T__51(pjavaLexer)
 *  -  void      pjavaLexer->T__52(pjavaLexer)
 *  -  void      pjavaLexer->T__53(pjavaLexer)
 *  -  void      pjavaLexer->T__54(pjavaLexer)
 *  -  void      pjavaLexer->T__55(pjavaLexer)
 *  -  void      pjavaLexer->T__56(pjavaLexer)
 *  -  void      pjavaLexer->T__57(pjavaLexer)
 *  -  void      pjavaLexer->T__58(pjavaLexer)
 *  -  void      pjavaLexer->T__59(pjavaLexer)
 *  -  void      pjavaLexer->T__60(pjavaLexer)
 *  -  void      pjavaLexer->T__61(pjavaLexer)
 *  -  void      pjavaLexer->T__62(pjavaLexer)
 *  -  void      pjavaLexer->T__63(pjavaLexer)
 *  -  void      pjavaLexer->T__64(pjavaLexer)
 *  -  void      pjavaLexer->T__65(pjavaLexer)
 *  -  void      pjavaLexer->T__66(pjavaLexer)
 *  -  void      pjavaLexer->T__67(pjavaLexer)
 *  -  void      pjavaLexer->T__68(pjavaLexer)
 *  -  void      pjavaLexer->T__69(pjavaLexer)
 *  -  void      pjavaLexer->T__70(pjavaLexer)
 *  -  void      pjavaLexer->T__71(pjavaLexer)
 *  -  void      pjavaLexer->T__72(pjavaLexer)
 *  -  void      pjavaLexer->T__73(pjavaLexer)
 *  -  void      pjavaLexer->T__74(pjavaLexer)
 *  -  void      pjavaLexer->T__75(pjavaLexer)
 *  -  void      pjavaLexer->T__76(pjavaLexer)
 *  -  void      pjavaLexer->T__77(pjavaLexer)
 *  -  void      pjavaLexer->T__78(pjavaLexer)
 *  -  void      pjavaLexer->T__79(pjavaLexer)
 *  -  void      pjavaLexer->T__80(pjavaLexer)
 *  -  void      pjavaLexer->T__81(pjavaLexer)
 *  -  void      pjavaLexer->T__82(pjavaLexer)
 *  -  void      pjavaLexer->T__83(pjavaLexer)
 *  -  void      pjavaLexer->T__84(pjavaLexer)
 *  -  void      pjavaLexer->T__85(pjavaLexer)
 *  -  void      pjavaLexer->T__86(pjavaLexer)
 *  -  void      pjavaLexer->T__87(pjavaLexer)
 *  -  void      pjavaLexer->T__88(pjavaLexer)
 *  -  void      pjavaLexer->T__89(pjavaLexer)
 *  -  void      pjavaLexer->T__90(pjavaLexer)
 *  -  void      pjavaLexer->T__91(pjavaLexer)
 *  -  void      pjavaLexer->T__92(pjavaLexer)
 *  -  void      pjavaLexer->T__93(pjavaLexer)
 *  -  void      pjavaLexer->T__94(pjavaLexer)
 *  -  void      pjavaLexer->T__95(pjavaLexer)
 *  -  void      pjavaLexer->T__96(pjavaLexer)
 *  -  void      pjavaLexer->T__97(pjavaLexer)
 *  -  void      pjavaLexer->T__98(pjavaLexer)
 *  -  void      pjavaLexer->T__99(pjavaLexer)
 *  -  void      pjavaLexer->T__100(pjavaLexer)
 *  -  void      pjavaLexer->T__101(pjavaLexer)
 *  -  void      pjavaLexer->T__102(pjavaLexer)
 *  -  void      pjavaLexer->T__103(pjavaLexer)
 *  -  void      pjavaLexer->T__104(pjavaLexer)
 *  -  void      pjavaLexer->T__105(pjavaLexer)
 *  -  void      pjavaLexer->T__106(pjavaLexer)
 *  -  void      pjavaLexer->T__107(pjavaLexer)
 *  -  void      pjavaLexer->T__108(pjavaLexer)
 *  -  void      pjavaLexer->T__109(pjavaLexer)
 *  -  void      pjavaLexer->T__110(pjavaLexer)
 *  -  void      pjavaLexer->T__111(pjavaLexer)
 *  -  void      pjavaLexer->T__112(pjavaLexer)
 *  -  void      pjavaLexer->T__113(pjavaLexer)
 *  -  void      pjavaLexer->HexLiteral(pjavaLexer)
 *  -  void      pjavaLexer->DecimalLiteral(pjavaLexer)
 *  -  void      pjavaLexer->OctalLiteral(pjavaLexer)
 *  -  void      pjavaLexer->HexDigit(pjavaLexer)
 *  -  void      pjavaLexer->IntegerTypeSuffix(pjavaLexer)
 *  -  void      pjavaLexer->FloatingPointLiteral(pjavaLexer)
 *  -  void      pjavaLexer->Exponent(pjavaLexer)
 *  -  void      pjavaLexer->FloatTypeSuffix(pjavaLexer)
 *  -  void      pjavaLexer->CharacterLiteral(pjavaLexer)
 *  -  void      pjavaLexer->StringLiteral(pjavaLexer)
 *  -  void      pjavaLexer->EscapeSequence(pjavaLexer)
 *  -  void      pjavaLexer->OctalEscape(pjavaLexer)
 *  -  void      pjavaLexer->UnicodeEscape(pjavaLexer)
 *  -  void      pjavaLexer->ENUM(pjavaLexer)
 *  -  void      pjavaLexer->Identifier(pjavaLexer)
 *  -  void      pjavaLexer->Letter(pjavaLexer)
 *  -  void      pjavaLexer->JavaIDDigit(pjavaLexer)
 *  -  void      pjavaLexer->WS(pjavaLexer)
 *  -  void      pjavaLexer->COMMENT(pjavaLexer)
 *  -  void      pjavaLexer->LINE_COMMENT(pjavaLexer)
 *  -  void      pjavaLexer->Tokens(pjavaLexer)
 *
 * The return type for any particular rule is of course determined by the source
 * grammar file.
 */
// [The "BSD licence"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef	_javaLexer_H
#define _javaLexer_H
/* =============================================================================
 * Standard antlr3 C runtime definitions
 */
#include    <antlr3.h>

/* End of standard antlr 3 runtime definitions
 * =============================================================================
 */
 
#ifdef __cplusplus
extern "C" {
#endif

// Forward declare the context typedef so that we can use it before it is
// properly defined. Delegators and delegates (from import statements) are
// interdependent and their context structures contain pointers to each other
// C only allows such things to be declared if you pre-declare the typedef.
//
typedef struct javaLexer_Ctx_struct javaLexer, * pjavaLexer;



#define	ANTLR3_INLINE_INPUT_ASCII


#ifdef	ANTLR3_WINDOWS
// Disable: Unreferenced parameter,							- Rules with parameters that are not used
//          constant conditional,							- ANTLR realizes that a prediction is always true (synpred usually)
//          initialized but unused variable					- tree rewrite variables declared but not needed
//          Unreferenced local variable						- lexer rule declares but does not always use _type
//          potentially unitialized variable used			- retval always returned from a rule 
//			unreferenced local function has been removed	- susually getTokenNames or freeScope, they can go without warnigns
//
// These are only really displayed at warning level /W4 but that is the code ideal I am aiming at
// and the codegen must generate some of these warnings by necessity, apart from 4100, which is
// usually generated when a parser rule is given a parameter that it does not use. Mostly though
// this is a matter of orthogonality hence I disable that one.
//
#pragma warning( disable : 4100 )
#pragma warning( disable : 4101 )
#pragma warning( disable : 4127 )
#pragma warning( disable : 4189 )
#pragma warning( disable : 4505 )
#pragma warning( disable : 4701 )
#endif

/** Context tracking structure for javaLexer
 */
struct javaLexer_Ctx_struct
{
    /** Built in ANTLR3 context tracker contains all the generic elements
     *  required for context tracking.
     */
    pANTLR3_LEXER    pLexer;


     void (*mT__24)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__25)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__26)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__27)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__28)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__29)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__30)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__31)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__32)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__33)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__34)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__35)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__36)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__37)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__38)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__39)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__40)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__41)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__42)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__43)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__44)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__45)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__46)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__47)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__48)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__49)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__50)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__51)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__52)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__53)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__54)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__55)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__56)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__57)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__58)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__59)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__60)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__61)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__62)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__63)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__64)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__65)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__66)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__67)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__68)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__69)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__70)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__71)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__72)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__73)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__74)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__75)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__76)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__77)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__78)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__79)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__80)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__81)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__82)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__83)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__84)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__85)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__86)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__87)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__88)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__89)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__90)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__91)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__92)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__93)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__94)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__95)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__96)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__97)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__98)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__99)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__100)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__101)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__102)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__103)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__104)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__105)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__106)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__107)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__108)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__109)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__110)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__111)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__112)	(struct javaLexer_Ctx_struct * ctx);
     void (*mT__113)	(struct javaLexer_Ctx_struct * ctx);
     void (*mHexLiteral)	(struct javaLexer_Ctx_struct * ctx);
     void (*mDecimalLiteral)	(struct javaLexer_Ctx_struct * ctx);
     void (*mOctalLiteral)	(struct javaLexer_Ctx_struct * ctx);
     void (*mHexDigit)	(struct javaLexer_Ctx_struct * ctx);
     void (*mIntegerTypeSuffix)	(struct javaLexer_Ctx_struct * ctx);
     void (*mFloatingPointLiteral)	(struct javaLexer_Ctx_struct * ctx);
     void (*mExponent)	(struct javaLexer_Ctx_struct * ctx);
     void (*mFloatTypeSuffix)	(struct javaLexer_Ctx_struct * ctx);
     void (*mCharacterLiteral)	(struct javaLexer_Ctx_struct * ctx);
     void (*mStringLiteral)	(struct javaLexer_Ctx_struct * ctx);
     void (*mEscapeSequence)	(struct javaLexer_Ctx_struct * ctx);
     void (*mOctalEscape)	(struct javaLexer_Ctx_struct * ctx);
     void (*mUnicodeEscape)	(struct javaLexer_Ctx_struct * ctx);
     void (*mENUM)	(struct javaLexer_Ctx_struct * ctx);
     void (*mIdentifier)	(struct javaLexer_Ctx_struct * ctx);
     void (*mLetter)	(struct javaLexer_Ctx_struct * ctx);
     void (*mJavaIDDigit)	(struct javaLexer_Ctx_struct * ctx);
     void (*mWS)	(struct javaLexer_Ctx_struct * ctx);
     void (*mCOMMENT)	(struct javaLexer_Ctx_struct * ctx);
     void (*mLINE_COMMENT)	(struct javaLexer_Ctx_struct * ctx);
     void (*mTokens)	(struct javaLexer_Ctx_struct * ctx);    const char * (*getGrammarFileName)();
    void	    (*free)   (struct javaLexer_Ctx_struct * ctx);
        
};

// Function protoypes for the constructor functions that external translation units
// such as delegators and delegates may wish to call.
//
ANTLR3_API pjavaLexer javaLexerNew         (pANTLR3_INPUT_STREAM instream);
ANTLR3_API pjavaLexer javaLexerNewSSD      (pANTLR3_INPUT_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state);

/** Symbolic definitions of all the tokens that the lexer will work with.
 * \{
 *
 * Antlr will define EOF, but we can't use that as it it is too common in
 * in C header files and that would be confusing. There is no way to filter this out at the moment
 * so we just undef it here for now. That isn't the value we get back from C recognizers
 * anyway. We are looking for ANTLR3_TOKEN_EOF.
 */
#ifdef	EOF
#undef	EOF
#endif
#ifdef	Tokens
#undef	Tokens
#endif 
#define T__29      29
#define T__28      28
#define T__27      27
#define T__26      26
#define FloatTypeSuffix      15
#define T__25      25
#define OctalLiteral      10
#define T__24      24
#define EOF      -1
#define Identifier      4
#define T__93      93
#define T__94      94
#define T__91      91
#define T__92      92
#define T__90      90
#define COMMENT      22
#define T__99      99
#define T__98      98
#define T__97      97
#define T__96      96
#define T__95      95
#define T__80      80
#define T__81      81
#define T__82      82
#define T__83      83
#define LINE_COMMENT      23
#define IntegerTypeSuffix      13
#define T__85      85
#define T__84      84
#define T__87      87
#define T__86      86
#define T__89      89
#define T__88      88
#define T__71      71
#define WS      21
#define T__72      72
#define T__70      70
#define FloatingPointLiteral      6
#define JavaIDDigit      20
#define T__76      76
#define T__75      75
#define T__74      74
#define Letter      19
#define EscapeSequence      16
#define T__73      73
#define T__79      79
#define T__78      78
#define T__77      77
#define T__68      68
#define T__69      69
#define T__66      66
#define T__67      67
#define T__64      64
#define T__65      65
#define T__62      62
#define T__63      63
#define CharacterLiteral      7
#define Exponent      14
#define T__61      61
#define T__60      60
#define HexDigit      12
#define T__55      55
#define T__56      56
#define T__57      57
#define T__58      58
#define T__51      51
#define T__52      52
#define T__53      53
#define T__54      54
#define T__107      107
#define T__108      108
#define T__109      109
#define T__59      59
#define T__103      103
#define T__104      104
#define T__105      105
#define T__106      106
#define T__111      111
#define T__110      110
#define T__113      113
#define T__112      112
#define T__50      50
#define T__42      42
#define HexLiteral      9
#define T__43      43
#define T__40      40
#define T__41      41
#define T__46      46
#define T__47      47
#define T__44      44
#define T__45      45
#define T__48      48
#define T__49      49
#define T__102      102
#define T__101      101
#define T__100      100
#define DecimalLiteral      11
#define StringLiteral      8
#define T__30      30
#define T__31      31
#define T__32      32
#define T__33      33
#define T__34      34
#define ENUM      5
#define T__35      35
#define T__36      36
#define T__37      37
#define T__38      38
#define T__39      39
#define UnicodeEscape      17
#define OctalEscape      18
#ifdef	EOF
#undef	EOF
#define	EOF	ANTLR3_TOKEN_EOF
#endif

#ifndef TOKENSOURCE
#define TOKENSOURCE(lxr) lxr->pLexer->rec->state->tokSource
#endif

/* End of token definitions for javaLexer
 * =============================================================================
 */
/** \} */

#ifdef __cplusplus
}
#endif

#endif

/* END - Note:Keep extra line feed to satisfy UNIX systems */
