#!/bin/sh

WD=../source-generator
GEN=$WD/generated

pushd $WD
qmake
make
./code
popd

mkdir -p umllib/generated
cp -rf $GEN/umllib/generated/* umllib/generated

cp -rf $GEN/umllib/uml_guiobjectfactory.cpp umllib/
cp -rf $GEN/repo/* repo/

rm -rf shapes
cp -rf $GEN/shapes .

cp -rf $GEN/qtreal.qrc .
