#!/bin/sh

WD=../unreal-tim
GEN=$WD/generated

pushd $WD
qmake
make
./code
popd

mkdir -p umllib/generated
cp -rf $GEN/umllib/generated/* umllib/generated

cp -rf $GEN/umllib/uml_guiobjectfactory.cpp umllib/

cp -rf $GEN/umllib/edges_stuff.cpp repo/
cp -rf $GEN/repo/* repo/

rm -rf shapes
cp -rf $GEN/shapes .

cp -rf $GEN/real_dynamic.qrc .
