#!/bin/sh

WD=../source-generator

pushd $WD
qmake
make
./code
popd

mkdir -p umllib/generated
cp -rf $WD/generated/umllib/generated/* umllib/generated


cp -rf $WD/generated/umllib/uml_guiobjectfactory.cpp umllib/
cp -rf $WD/generated/repo/* repo/

rm -rf shapes
cp -rf $WD/generated/shapes .

qmake
make
