#!/usr/bin/tclsh

set rules {
  CommaAtTheEnd
  CopyrightNotice
  IncludeGuards
  LineLength
  LineEndings
  NoSpacesAtTheStart
  NoRelativePathsInIncludes
  OpeningParethesisForClass
  NullsForbidden
}
