#ifndef BLUETOOTHACCELEROMETRSENSORIMPLEMENTATION_H
#define BLUETOOTHACCELEROMETRSENSORIMPLEMENTATION_H

class BluetoothAccelerometrSensorImplementation
{
public:
	BluetoothAccelerometrSensorImplementation();
};

#endif // BLUETOOTHACCELEROMETRSENSORIMPLEMENTATION_H
