#ifndef GENERATOR_GLOBAL_H
#define GENERATOR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GENERATOR_LIBRARY)
#  define GENERATORSHARED_EXPORT Q_DECL_EXPORT
#else
#  define GENERATORSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // GENERATOR_GLOBAL_H
