HEADERS += \
	nxtOSEK/elementGeneratorFactory.h \
	nxtOSEK/nxtFlashTool.h \
	nxtOSEK/nxtOSEKRobotGenerator.h \
	nxtOSEK/smartLine.h \
	nxtOSEK/generators/abstractElementGenerator.h \
	nxtOSEK/generators/functionElementGenerator.h \
	nxtOSEK/generators/ifElementGenerator.h \
	nxtOSEK/generators/loopElementGenerator.h \
	nxtOSEK/generators/listsmartline.h \
	nxtOSEK/generators/variables.h \
	nxtOSEK/generators/commentElementGenerator.h \
	nxtOSEK/generators/imageGenerator.h \
	nxtOSEK/generators/simpleElementFactory.h \
	nxtOSEK/generators/simpleElementGenerator.h \
	nxtOSEK/generators/simpleElements/abstractSimpleElementGenerator.h \
	nxtOSEK/generators/simpleElements/enginesStopGenerator.h \
	nxtOSEK/generators/simpleElements/timerGenerator.h \
	nxtOSEK/generators/simpleElements/beepGenerator.h \
	nxtOSEK/generators/simpleElements/playToneGenerator.h \
	nxtOSEK/generators/simpleElements/finalNodeGenerator.h \
	nxtOSEK/generators/simpleElements/nullificationEncoderGenerator.h \
	nxtOSEK/generators/simpleElements/waitForColorBlockGenerator.h \
	nxtOSEK/generators/simpleElements/waitForColorIntensityBlockGenerator.h \
	nxtOSEK/generators/simpleElements/balanceGenerator.h \
	nxtOSEK/generators/simpleElements/waitForLightBlockGenerator.h \
	nxtOSEK/generators/simpleElements/waitForSonarBlockGenerator.h \
	nxtOSEK/generators/simpleElements/waitForEncoderBlockGenerator.h \
	nxtOSEK/generators/simpleElements/waitForTouchSensorBlockGenerator.h \
	nxtOSEK/generators/simpleElements/variableInitGenerator.h \
	nxtOSEK/generators/simpleElements/balanceInitGenerator.h \
	nxtOSEK/generators/simpleElements/initialNodeGenerator.h \
	nxtOSEK/generators/simpleElements/enginesGenerator.h \
	nxtOSEK/generators/simpleElements/waitForSoundBlockGenerator.h \
	nxtOSEK/generators/simpleElements/waitForGyroscopeBlockGenerator.h \
	nxtOSEK/generators/simpleElements/waitForAccelerometerBlockGenerator.h \
	nxtOSEK/generators/simpleElements/drawPixelBlockGenerator.h \
	nxtOSEK/generators/simpleElements/waitForButtonsBlockGenerator.h \
	nxtOSEK/generators/simpleElements/drawLineBlockGenerator.h \
	nxtOSEK/generators/simpleElements/drawCircleBlockGenerator.h \
	nxtOSEK/generators/simpleElements/printTextBlockGenerator.h \
	nxtOSEK/generators/simpleElements/drawRectBlockGenerator.h \
	nxtOSEK/generators/simpleElements/clearScreenBlockGenerator.h \
	nxtOSEK/generators/simpleElements/drawBlockGenerator.h \
	nxtOSEK/generators/simpleElements/subprogramsSimpleGenerator.h \
    nxtOSEK/generators/subprogramsGenerator.h \
    nxtOSEK/generators/controlFlowGenerator.h

SOURCES += \
	nxtOSEK/elementGeneratorFactory.cpp \
	nxtOSEK/nxtFlashTool.cpp \
	nxtOSEK/nxtOSEKRobotGenerator.cpp \
	nxtOSEK/smartLine.cpp \
	nxtOSEK/generators/abstractElementGenerator.cpp \
	nxtOSEK/generators/functionElementGenerator.cpp \
	nxtOSEK/generators/ifElementGenerator.cpp \
	nxtOSEK/generators/loopElementGenerator.cpp \
	nxtOSEK/generators/listsmartline.cpp \
	nxtOSEK/generators/variables.cpp \
	nxtOSEK/generators/imageGenerator.cpp \
	nxtOSEK/generators/commentElementGenerator.cpp \
	nxtOSEK/generators/simpleElementFactory.cpp \
	nxtOSEK/generators/simpleElementGenerator.cpp \
	nxtOSEK/generators/simpleElements/abstractSimpleElementGenerator.cpp \
	nxtOSEK/generators/simpleElements/enginesStopGenerator.cpp \
	nxtOSEK/generators/simpleElements/timerGenerator.cpp \
	nxtOSEK/generators/simpleElements/beepGenerator.cpp \
	nxtOSEK/generators/simpleElements/playToneGenerator.cpp \
	nxtOSEK/generators/simpleElements/finalNodeGenerator.cpp \
	nxtOSEK/generators/simpleElements/nullificationEncoderGenerator.cpp \
	nxtOSEK/generators/simpleElements/waitForColorBlockGenerator.cpp \
	nxtOSEK/generators/simpleElements/waitForColorIntensityBlockGenerator.cpp \
	nxtOSEK/generators/simpleElements/balanceGenerator.cpp \
	nxtOSEK/generators/simpleElements/waitForLightBlockGenerator.cpp \
	nxtOSEK/generators/simpleElements/waitForSonarBlockGenerator.cpp \
	nxtOSEK/generators/simpleElements/waitForEncoderBlockGenerator.cpp \
	nxtOSEK/generators/simpleElements/waitForTouchSensorBlockGenerator.cpp \
	nxtOSEK/generators/simpleElements/variableInitGenerator.cpp \
	nxtOSEK/generators/simpleElements/balanceInitGenerator.cpp \
	nxtOSEK/generators/simpleElements/initialNodeGenerator.cpp \
	nxtOSEK/generators/simpleElements/enginesGenerator.cpp \
	nxtOSEK/generators/simpleElements/waitForSoundBlockGenerator.cpp \
	nxtOSEK/generators/simpleElements/waitForGyroscopeBlockGenerator.cpp \
	nxtOSEK/generators/simpleElements/waitForAccelerometerBlockGenerator.cpp \
	nxtOSEK/generators/simpleElements/drawPixelBlockGenerator.cpp \
	nxtOSEK/generators/simpleElements/waitForButtonsBlockGenerator.cpp \
	nxtOSEK/generators/simpleElements/drawLineBlockGenerator.cpp \
	nxtOSEK/generators/simpleElements/drawCircleBlockGenerator.cpp \
	nxtOSEK/generators/simpleElements/printTextBlockGenerator.cpp \
	nxtOSEK/generators/simpleElements/drawRectBlockGenerator.cpp \
	nxtOSEK/generators/simpleElements/clearScreenBlockGenerator.cpp \
	nxtOSEK/generators/simpleElements/drawBlockGenerator.cpp \
	nxtOSEK/generators/simpleElements/subprogramsSimpleGenerator.cpp \
    nxtOSEK/generators/subprogramsGenerator.cpp \
    nxtOSEK/generators/controlFlowGenerator.cpp
