HEADERS += \
	nxtOSEK/elementGeneratorFactory.h \
	nxtOSEK/nxtFlashTool.h \
	nxtOSEK/nxtOSEKRobotGenerator.h \
	nxtOSEK/smartLine.h \
	nxtOSEK/generators/abstractElementGenerator.h \
	nxtOSEK/generators/functionElementGenerator.h \
	nxtOSEK/generators/ifElementGenerator.h \
	nxtOSEK/generators/loopElementGenerator.h \
	nxtOSEK/generators/simpleElementGenerator.h \
	nxtOSEK/generators/simpleElements/abstractSimpleElementGenerator.h \
	nxtOSEK/generators/simpleElements/enginesForwardGenerator.h \
	nxtOSEK/generators/simpleElements/enginesBackwardGenerator.h \
	nxtOSEK/generators/simpleElements/enginesStopGenerator.h \
	nxtOSEK/generators/simpleElements/timerGenerator.h \
	nxtOSEK/generators/simpleElements/beepGenerator.h \
	nxtOSEK/generators/simpleElements/playToneGenerator.h \
	nxtOSEK/generators/simpleElements/finalNodeGenerator.h \
	nxtOSEK/generators/simpleElements/nullificationEncoderGenerator.h \
	nxtOSEK/generators/simpleElements/initialBlockGenerator.h \
	nxtOSEK/generators/simpleElements/waitForColorBlockGenerator.h \
	nxtOSEK/generators/simpleElements/waitForColorIntensityBlockGenerator.h \
	nxtOSEK/generators/simpleElements/balanceGenerator.h \
	nxtOSEK/generators/simpleElements/waitForLightBlockGenerator.h \
	nxtOSEK/generators/simpleElements/waitForSonarBlockGenerator.h \
	nxtOSEK/generators/simpleElements/waitForEncoderBlockGenerator.h \
	nxtOSEK/generators/simpleElements/waitForTouchSensorBlockGenerator.h \
	nxtOSEK/generators/simpleElements/variableInitGenerator.h \
	nxtOSEK/generators/simpleElements/balanceInitGenerator.h \
	nxtOSEK/generators/simpleElementFactory.h \
	nxtOSEK/generators/simpleElements/initialNodeGenerator.h

SOURCES += \
	nxtOSEK/elementGeneratorFactory.cpp \
	nxtOSEK/nxtFlashTool.cpp \
	nxtOSEK/nxtOSEKRobotGenerator.cpp \
	nxtOSEK/smartLine.cpp \
	nxtOSEK/generators/abstractElementGenerator.cpp \
	nxtOSEK/generators/functionElementGenerator.cpp \
	nxtOSEK/generators/ifElementGenerator.cpp \
	nxtOSEK/generators/loopElementGenerator.cpp \
	nxtOSEK/generators/simpleElementGenerator.cpp \
	nxtOSEK/generators/simpleElements/abstractSimpleElementGenerator.cpp \
	nxtOSEK/generators/simpleElements/enginesForwardGenerator.cpp \
	nxtOSEK/generators/simpleElements/enginesBackwardGenerator.cpp \
	nxtOSEK/generators/simpleElements/enginesStopGenerator.cpp \
	nxtOSEK/generators/simpleElements/timerGenerator.cpp \
	nxtOSEK/generators/simpleElements/beepGenerator.cpp \
	nxtOSEK/generators/simpleElements/playToneGenerator.cpp \
	nxtOSEK/generators/simpleElements/finalNodeGenerator.cpp \
	nxtOSEK/generators/simpleElements/nullificationEncoderGenerator.cpp \
	nxtOSEK/generators/simpleElements/initialBlockGenerator.cpp \
	nxtOSEK/generators/simpleElements/waitForColorBlockGenerator.cpp \
	nxtOSEK/generators/simpleElements/waitForColorIntensityBlockGenerator.cpp \
	nxtOSEK/generators/simpleElements/balanceGenerator.cpp \
	nxtOSEK/generators/simpleElements/waitForLightBlockGenerator.cpp \
	nxtOSEK/generators/simpleElements/waitForSonarBlockGenerator.cpp \
	nxtOSEK/generators/simpleElements/waitForEncoderBlockGenerator.cpp \
	nxtOSEK/generators/simpleElements/waitForTouchSensorBlockGenerator.cpp \
	nxtOSEK/generators/simpleElements/variableInitGenerator.cpp \
	nxtOSEK/generators/simpleElements/balanceInitGenerator.cpp \
	nxtOSEK/generators/simpleElementFactory.cpp \
	nxtOSEK/generators/simpleElements/initialNodeGenerator.cpp
