######################################################################
# Automatically generated by qmake (2.01a) ?? ????? 17 19:41:44 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += gemake.h \
           interpreter.h \
           ../../../../unreal/trunk/qrrepo/repoApi.h \
           ../../../../unreal/trunk/qrgui/kernel/roles.h \
	   ../../../../unreal/trunk/qrgui/kernel/ids.h \
	   ../../../../unreal/trunk/qrrepo/private/client.h \
	   ../../../../unreal/trunk/qrgui/kernel/definitions.h \
           ../../../../unreal/trunk/qrrepo/private/classes/object.h \
           ../../../../unreal/trunk/qrrepo/private/qrRepoGlobal.h \
           ../../../../unreal/trunk/qrrepo/private/serializer.h \
           ../../../../unreal/trunk/qrrepo/repoControlInterface.h \
           ../../../../unreal/trunk/qrrepo/commonRepoApi.h \
           ../../../../unreal/trunk/qrrepo/graphicalRepoApi.h \
           ../../../../unreal/trunk/qrrepo/logicalRepoApi.h
SOURCES += gemake.cpp \
           interpreter.cpp \
           main.cpp \
	   ../../../../unreal/trunk/qrgui/kernel/ids.cpp \
           ../../../../unreal/trunk/qrrepo/private/client.cpp \
	   ../../../../unreal/trunk/qrrepo/private/classes/object.cpp \
	   ../../../../unreal/trunk/qrrepo/private/serializer.cpp

LIBS += -L../../../../unreal/trunk/qrgui -lqrrepo

QMAKE_LFLAGS="-Wl,-O1,-rpath,$(PWD)/../../../../unreal/trunk/qrgui"

