#generators/nxtOSEK/nxtOSEKfuncOrientedGenerator/elementGenerators/
HEADERS += generators/nxtOSEK/nxtOSEKfuncOrientedGenerator.h
HEADERS += generators/nxtOSEK/nxtOSEKfuncOrientedGenerator/abstractElementGenerator.h \
	generators/nxtOSEK/nxtOSEKfuncOrientedGenerator/elementGeneratorFactory.h

SOURCES += generators/nxtOSEK/nxtOSEKfuncOrientedGenerator/nxtOSEKfuncOrientedGenerator.cpp \
	generators/nxtOSEK/nxtOSEKfuncOrientedGenerator/elementGeneratorFactory.cpp \
	generators/nxtOSEK/nxtOSEKfuncOrientedGenerator/abstractElementGenerator.cpp

#simpleElements/
HEADERS += generators/nxtOSEK/nxtOSEKfuncOrientedGenerator/elementGenerators/simpleElementGenerator.h
SOURCES += generators/nxtOSEK/nxtOSEKfuncOrientedGenerator/elementGenerators/simpleElementGenerator.cpp

HEADERS += generators/nxtOSEK/nxtOSEKfuncOrientedGenerator/elementGenerators/simpleElements/beep_gen.h \
	generators/nxtOSEK/nxtOSEKfuncOrientedGenerator/elementGenerators/simpleElements/enginesBackward_gen.h \
	generators/nxtOSEK/nxtOSEKfuncOrientedGenerator/elementGenerators/simpleElements/enginesForward_gen.h \
	generators/nxtOSEK/nxtOSEKfuncOrientedGenerator/elementGenerators/simpleElements/enginesStop_gen.h \
	generators/nxtOSEK/nxtOSEKfuncOrientedGenerator/elementGenerators/simpleElements/finalNode_gen.h \
	generators/nxtOSEK/nxtOSEKfuncOrientedGenerator/elementGenerators/simpleElements/initialBlock_gen.h \
	generators/nxtOSEK/nxtOSEKfuncOrientedGenerator/elementGenerators/simpleElements/initialNode_gen.h \
	generators/nxtOSEK/nxtOSEKfuncOrientedGenerator/elementGenerators/simpleElements/nullificationEncoder_gen.h \
	generators/nxtOSEK/nxtOSEKfuncOrientedGenerator/elementGenerators/simpleElements/playTone_gen.h \
	generators/nxtOSEK/nxtOSEKfuncOrientedGenerator/elementGenerators/simpleElements/timer_gen.h \
	generators/nxtOSEK/nxtOSEKfuncOrientedGenerator/elementGenerators/simpleElements/waitForColor_gen.h \
	generators/nxtOSEK/nxtOSEKfuncOrientedGenerator/elementGenerators/simpleElements/waitForColorIntensity_gen.h \
	generators/nxtOSEK/nxtOSEKfuncOrientedGenerator/elementGenerators/simpleElements/waitForEncoder_gen.h \
	generators/nxtOSEK/nxtOSEKfuncOrientedGenerator/elementGenerators/simpleElements/waitForSonarDistance_gen.h \
	generators/nxtOSEK/nxtOSEKfuncOrientedGenerator/elementGenerators/simpleElements/waitForTouchSensor_gen.h \
	generators/nxtOSEK/nxtOSEKfuncOrientedGenerator/elementGenerators/simpleElements/function_gen.h

SOURCES += generators/nxtOSEK/nxtOSEKfuncOrientedGenerator/elementGenerators/simpleElements/beep_gen.cpp \
	generators/nxtOSEK/nxtOSEKfuncOrientedGenerator/elementGenerators/simpleElements/enginesBackward_gen.cpp \
	generators/nxtOSEK/nxtOSEKfuncOrientedGenerator/elementGenerators/simpleElements/enginesForward_gen.cpp \
	generators/nxtOSEK/nxtOSEKfuncOrientedGenerator/elementGenerators/simpleElements/enginesStop_gen.cpp \
	generators/nxtOSEK/nxtOSEKfuncOrientedGenerator/elementGenerators/simpleElements/finalNode_gen.cpp \
	generators/nxtOSEK/nxtOSEKfuncOrientedGenerator/elementGenerators/simpleElements/initialBlock_gen.cpp \
	generators/nxtOSEK/nxtOSEKfuncOrientedGenerator/elementGenerators/simpleElements/initialNode_gen.cpp \
	generators/nxtOSEK/nxtOSEKfuncOrientedGenerator/elementGenerators/simpleElements/nullificationEncoder_gen.cpp \
	generators/nxtOSEK/nxtOSEKfuncOrientedGenerator/elementGenerators/simpleElements/playTone_gen.cpp \
	generators/nxtOSEK/nxtOSEKfuncOrientedGenerator/elementGenerators/simpleElements/timer_gen.cpp \
	generators/nxtOSEK/nxtOSEKfuncOrientedGenerator/elementGenerators/simpleElements/waitForColor_gen.cpp \
	generators/nxtOSEK/nxtOSEKfuncOrientedGenerator/elementGenerators/simpleElements/waitForColorIntensity_gen.cpp \
	generators/nxtOSEK/nxtOSEKfuncOrientedGenerator/elementGenerators/simpleElements/waitForEncoder_gen.cpp \
	generators/nxtOSEK/nxtOSEKfuncOrientedGenerator/elementGenerators/simpleElements/waitForSonarDistance_gen.cpp \
	generators/nxtOSEK/nxtOSEKfuncOrientedGenerator/elementGenerators/simpleElements/waitForTouchSensor_gen.cpp \
	generators/nxtOSEK/nxtOSEKfuncOrientedGenerator/elementGenerators/simpleElements/function_gen.cpp

HEADERS += generators/nxtOSEK/nxtOSEKfuncOrientedGenerator/elementGenerators/loop_gen.h
SOURCES += generators/nxtOSEK/nxtOSEKfuncOrientedGenerator/elementGenerators/loop_gen.cpp

HEADERS += generators/nxtOSEK/nxtOSEKfuncOrientedGenerator/elementGenerators/ifBlock_gen.h
SOURCES += generators/nxtOSEK/nxtOSEKfuncOrientedGenerator/elementGenerators/ifBlock_gen.cpp
