######################################################################
# Automatically generated by qmake (2.01a) ?? ???? 30 13:59:05 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += codeArea.h codeEditor.h textHighlighter.h
SOURCES += codeArea.cpp codeEditor.cpp main.cpp textHighlighter.cpp
